namespace Swimomatic
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SwimomaticEntityContext class is the context for the project.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Generated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    public class SwimomaticEntityContext : _SwimomaticEntityContext
    {
        
        #region Constructor
        public SwimomaticEntityContext()
        {
        }
        #endregion
        
        public SwimomaticEntityContext(string connectionString) : 
                base(connectionString)
        {
        }
    }
}
