
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_PoolConfigGetByHeatSheetEventID
	end
go

create procedure dbo.usp_PoolConfigGetByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetByHeatSheetEventID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/14/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the PoolConfig Entity
 The Entity expects the following properties to be returned:
   LaneCount < System.Int32 >
   ActualLaneLength < System.Int32 >
   PoolConfigID < System.Int32 >
   UOMID < System.Int32 >
   NominalLaneLength < System.Int32 >
   NominalUOMID < System.Int32 >
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	select	 pc.CreatedByUserID
			,pc.CreatedDate
			,pc.[Description]
			,pc.LaneCount
			,pc.LaneLength
			,pc.ModifiedByUserID
			,pc.ModifiedDate
			,pc.PoolConfigID
			,pc.PoolID
			,pc.UOMID
	from dbo.PoolConfig pc
	inner join dbo.HeatSheet hst on hst.PoolConfigID = pc.PoolConfigID
	inner join dbo.HeatSheetEvent hse on hse.HeatSheetID = hst.HeatSheetID
	where hse.HeatSheetEventID = @HeatSheetEventID
		
go

