
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimEventGet')
	begin
	    drop procedure dbo.usp_SwimEventGet
	end
go

create procedure dbo.usp_SwimEventGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimEventGet
 
 Description:		Selects a SwimEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/3/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimEvent Entity
 The Entity expects the following properties to be returned:
   AgeClassID < System.Int32 >
   Description < System.String >
   StrokeID < System.Int32 >
   SwimEventID < System.Int32 >
 ********************************************************************************************************/
 @SwimEventID int

as
	select
		 AgeClassID
		,Description
		,StrokeID
		,SwimEventID
	from dbo.SwimEvent
	where
		SwimEventID = @SwimEventID
		
go

