
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetByTeamSeasonID')
	begin
	    drop procedure dbo.usp_SeasonGetByTeamSeasonID
	end
go

create procedure dbo.usp_SeasonGetByTeamSeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetByTeamSeasonID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/20/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
 ********************************************************************************************************/
 @TeamSeasonID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
	from dbo.Season s
	inner join dbo.TeamSeason ts on ts.SeasonID = s.SeasonID
	where ts.TeamSeasonID = @TeamSeasonID
		
go

