
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamSeasonGet')
	begin
	    drop procedure dbo.usp_TeamSeasonGet
	end
go

create procedure dbo.usp_TeamSeasonGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamSeasonGet
 
 Description:		Selects a TeamSeason record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the TeamSeason Entity
 The Entity expects the following properties to be returned:
   SeasonID < System.Int32 >
   TeamID < System.Int32 >
   TeamSeasonID < System.Int32 >
 ********************************************************************************************************/
 @TeamSeasonID int

as
	select
		 SeasonID
		,TeamID
		,TeamSeasonID
	from dbo.TeamSeason
	where
		TeamSeasonID = @TeamSeasonID
		
go

