
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSwimmerGetAllBySwimMeetID')
	begin
	    drop procedure dbo.usp_HeatSwimmerGetAllBySwimMeetID
	end
go

create procedure dbo.usp_HeatSwimmerGetAllBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSwimmerGetAllBySwimMeetID
 
 Description:		Selects a HeatSwimmer record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/9/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int

as
	select
		 hs.HeatID
		,hs.HeatSwimmerID
		,hs.LaneNumber
		,hs.Leg
		,hs.SwimmerTeamSeasonID
		,s.SwimmerID
		,s.FirstName
		,s.LastName
		,s.BirthDate
		,t.Abbrev
		,coalesce(seed.ElapsedTime, 0) as SeedTime
		,coalesce(r.Disqualified,0) as Disqualified
		,coalesce(r.ElapsedTime,0) as ElapsedTime
		,coalesce(r.Split,0) as Split
	from dbo.HeatSwimmer hs
	left outer join dbo.Result r on r.HeatSwimmerID = hs.HeatSwimmerID
	left outer join dbo.Result seed on seed.ResultID = hs.SeedResultID
	inner join dbo.Heat h on h.HeatID = hs.HeatID
	inner join dbo.HeatSheetEvent hse on hse.HeatSheetEventID = h.HeatSheetEventID
	inner join dbo.HeatSheet hst on hst.HeatSheetID = hse.HeatSheetID
	inner join dbo.SwimmerTeamSeason sts on sts.SwimmerTeamSeasonID = hs.SwimmerTeamSeasonID
	inner join dbo.Swimmer s on s.SwimmerID = sts.SwimmerID
	inner join dbo.TeamSeason ts on ts.TeamSeasonID = sts.TeamSeasonID
	inner join dbo.Team t on t.TeamID = ts.TeamID
	where hst.SwimMeetID = @SwimMeetID
		
go

