
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetEventGetBySwimEventIDSwimMeetID')
	begin
	    drop procedure dbo.usp_SwimMeetEventGetBySwimEventIDSwimMeetID
	end
go

create procedure dbo.usp_SwimMeetEventGetBySwimEventIDSwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetEventGetBySwimEventIDSwimMeetID
 
 Description:		Selects a SwimMeetEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/22/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimMeetEvent Entity
 The Entity expects the following properties to be returned:
   Sequence < System.Int16 >
   SwimEventID < System.Int32 >
   SwimMeetEventID < System.Int32 >
   SwimMeetID < System.Int32 >
   Distance < System.Int32 >
 ********************************************************************************************************/
 @SwimEventID int
,@SwimMeetID int

as
	select
		 [Sequence]
		,SwimEventID
		,SwimMeetEventID
		,SwimMeetID
		,Distance
	from dbo.SwimMeetEvent
	where SwimEventID = @SwimEventID
	and	SwimMeetID = @SwimMeetID
		
go

