
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetAllByUserTeamID')
	begin
	    drop procedure dbo.usp_PoolConfigGetAllByUserTeamID
	end
go

create procedure dbo.usp_PoolConfigGetAllByUserTeamID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetAllByUserTeamID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 2/23/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @UserTeamID int

as

	--Get the location of the Team's HomePoolConfig
	declare @LocationID int
	select @LocationID = l.LocationID
	from dbo.Location l
	inner join dbo.[Pool] p on p.LocationID = l.LocationID
	inner join dbo.PoolConfig pc on pc.PoolID = p.PoolID
	inner join dbo.Team t on t.HomePoolConfigID = pc.PoolConfigID
	inner join dbo.UserTeam ut on ut.TeamID = t.TeamID
	where ut.UserTeamID = @UserTeamID

	--return all the PoolConfigs at the above location
	select
		 pc.LaneCount
		,pc.LaneLength
		,pc.PoolConfigID
		,pc.UOMID
		,pc.[Description]
		,pc.PoolID
		,pc.CreatedByUserID
		,pc.CreatedDate
		,pc.ModifiedByUserID
		,pc.ModifiedDate
		,l.[Address]
		,l.City
		,l.Latitude
		,l.LocationID
		,l.Longitude
		,l.Name as LocationName
		,l.PostalCode
		,l.RegionID
		,r.RegionAbbrev
	from dbo.PoolConfig pc
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.Location l on l.LocationID = p.LocationID
	inner join dbo.Region r on r.RegionID = l.RegionID
	where l.LocationID = @LocationID
		
go

