
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimEventGetAll')
	begin
	    drop procedure dbo.usp_SwimEventGetAll
	end
go

create procedure dbo.usp_SwimEventGetAll
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimEventGetAll
 
 Description:		Selects a SwimEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/12/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimEvent Entity
 The Entity expects the following properties to be returned:
   AgeClassID < System.Int32 >
   Description < System.String >
   StrokeID < System.Int32 >
   SwimEventID < System.Int32 >
 ********************************************************************************************************/

as
	select
		 se.AgeClassID
		,se.Description
		,se.StrokeID
		,se.SwimEventID
	from dbo.SwimEvent se
	inner join dbo.AgeClass ac on ac.AgeClassID = se.AgeClassID
	inner join dbo.Stroke s on s.StrokeID = se.StrokeID
	order by ac.MaxAge, s.Description
		
go

