if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerSave')
	begin
	    drop procedure dbo.usp_SwimmerSave
	end
go

create procedure dbo.usp_SwimmerSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerSave

 Description:		Saves an Swimmer record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @BirthDate datetime
	,@FirstName varchar(50)
,@IsMale bit
	,@LastName varchar(50)
,@SwimmerID int

as
	declare @InsertedPrimaryKeyTable table (SwimmerID int)
		
	if exists (select 1 from dbo.Swimmer where SwimmerID = @SwimmerID)
		begin
			
			update dbo.Swimmer
			set
				 BirthDate = @BirthDate
				,FirstName = @FirstName
				,IsMale = @IsMale
				,LastName = @LastName
			output inserted.SwimmerID into @InsertedPrimaryKeyTable
			where SwimmerID = @SwimmerID
		end
	else
		begin
			insert into dbo.Swimmer(
				 BirthDate
				,FirstName
				,IsMale
				,LastName
			)
			output inserted.SwimmerID into @InsertedPrimaryKeyTable
			values (
				 @BirthDate
				,@FirstName
				,@IsMale
				,@LastName
			)
			
		end

	select SwimmerID from @InsertedPrimaryKeyTable
		
go

