
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatGet')
	begin
	    drop procedure dbo.usp_HeatGet
	end
go

create procedure dbo.usp_HeatGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatGet
 
 Description:		Selects a Heat record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatID int

as
	select
		 HeatID
		,HeatNumber
		,HeatSheetEventID
	from dbo.Heat
	where
		HeatID = @HeatID
		
go

