
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerTeamRequestGet')
	begin
	    drop procedure dbo.usp_SwimmerTeamRequestGet
	end
go

create procedure dbo.usp_SwimmerTeamRequestGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerTeamRequestGet
 
 Description:		Selects a SwimmerTeamRequest record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/8/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimmerTeamRequest Entity
 The Entity expects the following properties to be returned:
   ApprovalDate < System.DateTime >
   ApprovalUserID < System.Int32 >
   IsApproved < System.Boolean >
   RequestDate < System.DateTime >
   SwimmerTeamRequestID < System.Int32 >
   TeamSeasonID < System.Int32 >
   UserSwimmerID < System.Int32 >
 ********************************************************************************************************/
 @SwimmerTeamRequestID int

as
	select
		 ApprovalDate
		,ApprovalUserID
		,IsApproved
		,RequestDate
		,SwimmerTeamRequestID
		,TeamSeasonID
		,UserSwimmerID
	from dbo.SwimmerTeamRequest
	where
		SwimmerTeamRequestID = @SwimmerTeamRequestID
		
go

