
if exists (select * from sysobjects where type = 'P' and name = 'usp_LeagueGetBySeasonID')
	begin
	    drop procedure dbo.usp_LeagueGetBySeasonID
	end
go

create procedure dbo.usp_LeagueGetBySeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LeagueGetBySeasonID
 
 Description:		Selects a League record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/21/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the League Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   LeagueID < System.Int32 >
   LeagueName < System.String >
   AgeClassRuleID < System.Int32 >
   RegionID < System.Int32 >
 ********************************************************************************************************/
 @SeasonID int

as
	select
		 l.[Description]
		,l.LeagueID
		,l.LeagueName
		,s.AgeClassRuleID
		,l.RegionID
	from dbo.League l
	inner join dbo.Season s on s.LeagueID = l.LeagueID
	where s.SeasonID = @SeasonID
		
go

