if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSwimmerSave')
	begin
	    drop procedure dbo.usp_HeatSwimmerSave
	end
go

create procedure dbo.usp_HeatSwimmerSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSwimmerSave

 Description:		Saves an HeatSwimmer record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/9/2009	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatID int
,@HeatSwimmerID int
,@LaneNumber int
,@Leg int
,@SeedResultID int
,@SwimmerTeamSeasonID int

as
	declare @InsertedPrimaryKeyTable table (HeatSwimmerID int)
	
	if @SeedResultID = 0 set @SeedResultID = null
	if @LaneNumber = 0 select @LaneNumber = isnull(max(LaneNumber) + 1, 1) from dbo.HeatSwimmer where HeatID = @HeatID	
	if @Leg = 0 select @Leg = isnull(max(Leg) + 1, 1) from dbo.HeatSwimmer where HeatID = @HeatID and isnull(LaneNumber,0) = @LaneNumber
		
	if exists (select 1 from dbo.HeatSwimmer where HeatSwimmerID = @HeatSwimmerID)
		begin			
			update dbo.HeatSwimmer
			set
				 HeatID = @HeatID
				,LaneNumber = @LaneNumber
				,Leg = @Leg
				,SeedResultID = @SeedResultID
				,SwimmerTeamSeasonID = @SwimmerTeamSeasonID
			output inserted.HeatSwimmerID into @InsertedPrimaryKeyTable
			where HeatSwimmerID = @HeatSwimmerID
		end
	else
		begin
			insert into dbo.HeatSwimmer(
				 HeatID
				,LaneNumber
				,Leg
				,SeedResultID
				,SwimmerTeamSeasonID
			)
			output inserted.HeatSwimmerID into @InsertedPrimaryKeyTable
			values (
				 @HeatID
				,@LaneNumber
				,@Leg
				,@SeedResultID
				,@SwimmerTeamSeasonID
			)
			
		end

	select HeatSwimmerID from @InsertedPrimaryKeyTable
		
go

