
if exists (select * from sysobjects where type = 'P' and name = 'usp_UserTeamGetAllByTeamSeasonID')
	begin
	    drop procedure dbo.usp_UserTeamGetAllByTeamSeasonID
	end
go

create procedure dbo.usp_UserTeamGetAllByTeamSeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserTeamGetAllByTeamSeasonID
 
 Description:		Selects a UserTeam record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/15/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the UserTeam Entity
 The Entity expects the following properties to be returned:
   SystemUserID < System.Int32 >
   TeamSeasonID < System.Int32 >
   UserTeamSeasonID < System.Int32 >
 ********************************************************************************************************/
 @TeamSeasonID int

as
	select
		 ut.SystemUserID
		,ut.TeamID
		,ut.UserTeamID
	from dbo.UserTeam ut
	inner join dbo.TeamSeason ts on ts.TeamID = ut.TeamID
	where ts.TeamSeasonID = @TeamSeasonID
		
go

