if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonScoringSchemeSave')
	begin
	    drop procedure dbo.usp_SeasonScoringSchemeSave
	end
go

create procedure dbo.usp_SeasonScoringSchemeSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonScoringSchemeSave

 Description:		Saves an SeasonScoringScheme record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/11/2011	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @ScoringSchemeID int
,@SeasonID int
,@SeasonScoringSchemeID int
,@SwimMeetTypeID int

as
	declare @InsertedPrimaryKeyTable table (SeasonScoringSchemeID int)
		
	if exists (select 1 from dbo.SeasonScoringScheme where SeasonScoringSchemeID = @SeasonScoringSchemeID)
		begin
			
			update dbo.SeasonScoringScheme
			set
				 ScoringSchemeID = @ScoringSchemeID
				,SeasonID = @SeasonID
				,SwimMeetTypeID = @SwimMeetTypeID
			output inserted.SeasonScoringSchemeID into @InsertedPrimaryKeyTable
			where SeasonScoringSchemeID = @SeasonScoringSchemeID
		end
	--prevent duplicates
	if exists(select 1 from dbo.SeasonScoringScheme where ScoringSchemeID = @ScoringSchemeID and SeasonID = @SeasonID and SwimMeetTypeID = @SwimMeetTypeID)
		begin
			insert into @InsertedPrimaryKeyTable
			select SeasonScoringSchemeID from dbo.SeasonScoringScheme where ScoringSchemeID = @ScoringSchemeID and SeasonID = @SeasonID and SwimMeetTypeID = @SwimMeetTypeID
		end
	else
		begin
			insert into dbo.SeasonScoringScheme(
				 ScoringSchemeID
				,SeasonID
				,SwimMeetTypeID
			)
			output inserted.SeasonScoringSchemeID into @InsertedPrimaryKeyTable
			values (
				 @ScoringSchemeID
				,@SeasonID
				,@SwimMeetTypeID
			)
			
		end

	select SeasonScoringSchemeID from @InsertedPrimaryKeyTable
		
go

