
if exists (select * from sysobjects where type = 'P' and name = 'usp_ScoreGetAllBySwimmerIDSwimMeetID')
	begin
	    drop procedure dbo.usp_ScoreGetAllBySwimmerIDSwimMeetID
	end
go

create procedure dbo.usp_ScoreGetAllBySwimmerIDSwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ScoreGetAllBySwimmerIDSwimMeetID
 
 Description:		Selects a Score record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 2/12/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Score Entity
 The Entity expects the following properties to be returned:
   SwimMeetID < System.Int32 >
   Disqualified < System.Boolean >
   TeamID < System.Int32 >
   ElapsedTime < System.Double >
   Swimmer < System.String >
   LaneLength < System.Double >
   Abbrev < System.String >
   Description < System.String >
   SwimmerID < System.Int32 >
   IsRelay < System.Boolean >
   EventDate < System.DateTime >
   Split < System.Double >
   IsCertified < System.Boolean >
   IsProtested < System.Boolean >
   Place < System.Int32 >
   Points < System.Double >
 ********************************************************************************************************/
 @SwimmerID int
,@SwimMeetID int

as
	select
		 SwimMeetID
		,HeatSheetID
		,HeatSheetEventID
		,HeatSwimmerID
		,Disqualified
		,TeamID
		,ElapsedTime
		,Swimmer
		,LaneLength
		,Abbrev
		,Description
		,SwimmerID
		,IsRelay
		,EventDate
		,Split
		,IsCertified
		,IsProtested
		,Place
		,Points
	from dbo.Score
	where
		SwimmerID = @SwimmerID
	and	SwimMeetID = @SwimMeetID
		
go

