
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetByHeatSheetID')
	begin
	    drop procedure dbo.usp_PoolConfigGetByHeatSheetID
	end
go

create procedure dbo.usp_PoolConfigGetByHeatSheetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetByHeatSheetID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/7/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetID int

as
	select	 pc.CreatedByUserID
			,pc.CreatedDate
			,pc.[Description]
			,pc.LaneCount
			,pc.LaneLength
			,pc.ModifiedByUserID
			,pc.ModifiedDate
			,pc.PoolConfigID
			,pc.PoolID
			,pc.UOMID
			,l.Name as LocationName
			,u.Abbrev as UOMAbbrev
			,p.[Description] as PoolDescription
	from dbo.PoolConfig pc
	inner join dbo.HeatSheet hs on hs.PoolConfigID = pc.PoolConfigID
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.UOM u on u.UOMID = pc.UOMID
	inner join dbo.SwimMeet sm on sm.SwimMeetID = hs.SwimMeetID
	inner join dbo.Location l on l.LocationID = sm.LocationID
	where hs.HeatSheetID = @HeatSheetID

go

