if exists (select * from sysobjects where type = 'P' and name = 'usp_UserLeagueSave')
	begin
	    drop procedure dbo.usp_UserLeagueSave
	end
go

create procedure dbo.usp_UserLeagueSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserLeagueSave

 Description:		Saves an UserLeague record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/9/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @LeagueID int
,@SystemUserID int
,@UserLeagueID int

as
	declare @InsertedPrimaryKeyTable table (UserLeagueID int)
		
	if exists (select 1 from dbo.UserLeague where UserLeagueID = @UserLeagueID)
		begin
			
			update dbo.UserLeague
			set
				 LeagueID = @LeagueID
				,SystemUserID = @SystemUserID
			output inserted.UserLeagueID into @InsertedPrimaryKeyTable
			where UserLeagueID = @UserLeagueID
		end
	--prevent duplicates
	if exists(select 1 from dbo.UserLeague where SystemUserID = @SystemUserID and LeagueID = @LeagueID)
		begin
			insert into @InsertedPrimaryKeyTable
			select UserLeagueID from dbo.UserLeague where SystemUserID = @SystemUserID and LeagueID = @LeagueID
		end
	else
		begin
			insert into dbo.UserLeague(
				 LeagueID
				,SystemUserID
			)
			output inserted.UserLeagueID into @InsertedPrimaryKeyTable
			values (
				 @LeagueID
				,@SystemUserID
			)
			
		end

	select UserLeagueID from @InsertedPrimaryKeyTable
		
go

