
if exists (select * from sysobjects where type = 'P' and name = 'usp_ScoringSchemeGetAllByUSASwimmingScoringEventTypeID')
	begin
	    drop procedure dbo.usp_ScoringSchemeGetAllByUSASwimmingScoringEventTypeID
	end
go

create procedure dbo.usp_ScoringSchemeGetAllByUSASwimmingScoringEventTypeID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ScoringSchemeGetAllByUSASwimmingScoringEventTypeID
 
 Description:		Selects a ScoringScheme record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/10/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the ScoringScheme Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   IndividualPoints < System.String >
   IsUSASwimming < System.Boolean >
   LaneCount < System.Int32 >
   RelayPoints < System.String >
   ScoringEventTypeID < System.Int32 >
   ScoringSchemeID < System.Int32 >
   SwimMeetTypeID < System.Int32 >
 ********************************************************************************************************/
 @IsUSASwimming bit
,@ScoringEventTypeID int

as
	select
		 Description
		,IndividualPoints
		,IsUSASwimming
		,LaneCount
		,RelayPoints
		,ScoringEventTypeID
		,ScoringSchemeID
	from dbo.ScoringScheme
	where
		IsUSASwimming = @IsUSASwimming
	and	ScoringEventTypeID = @ScoringEventTypeID
		
go

