if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolSave')
	begin
	    drop procedure dbo.usp_PoolSave
	end
go

create procedure dbo.usp_PoolSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolSave

 Description:		Saves an Pool record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/29/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @CreatedByUserID int
,@CreatedDate datetime
,@Description varchar(50)
,@LocationID int
,@ModifiedByUserID int
,@ModifiedDate datetime
,@PoolID int

as
	if @ModifiedByUserID = 0 set @ModifiedByUserID = null

	declare @InsertedPrimaryKeyTable table (PoolID int)
		
	if exists (select 1 from dbo.Pool where PoolID = @PoolID)
		begin
			
			update dbo.Pool
			set
				 CreatedByUserID = @CreatedByUserID
				,CreatedDate = @CreatedDate
				,[Description] = @Description
				,LocationID = @LocationID
				,ModifiedByUserID = @ModifiedByUserID
				,ModifiedDate = @ModifiedDate
			output inserted.PoolID into @InsertedPrimaryKeyTable
			where PoolID = @PoolID
		end
	else
		begin
			insert into dbo.Pool(
				 CreatedByUserID
				,CreatedDate
				,[Description]
				,LocationID
				,ModifiedByUserID
				,ModifiedDate
			)
			output inserted.PoolID into @InsertedPrimaryKeyTable
			values (
				 @CreatedByUserID
				,@CreatedDate
				,@Description
				,@LocationID
				,@ModifiedByUserID
				,@ModifiedDate
			)
			
		end

	select PoolID from @InsertedPrimaryKeyTable
		
go

