
if exists (select * from sysobjects where type = 'P' and name = 'usp_UserSwimmerGet')
	begin
	    drop procedure dbo.usp_UserSwimmerGet
	end
go

create procedure dbo.usp_UserSwimmerGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserSwimmerGet
 
 Description:		Selects a UserSwimmer record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/14/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the UserSwimmer Entity
 The Entity expects the following properties to be returned:
   SwimmerID < System.Int32 >
   SystemUserID < System.Int32 >
   UserSwimmerID < System.Int32 >
 ********************************************************************************************************/
 @UserSwimmerID int

as
	select
		 SwimmerID
		,SystemUserID
		,UserSwimmerID
	from dbo.UserSwimmer
	where
		UserSwimmerID = @UserSwimmerID
		
go

