if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerTeamRequestSave')
	begin
	    drop procedure dbo.usp_SwimmerTeamRequestSave
	end
go

create procedure dbo.usp_SwimmerTeamRequestSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerTeamRequestSave

 Description:		Saves an SwimmerTeamRequest record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/8/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @ApprovalDate date
,@ApprovalUserID int
,@IsApproved bit
,@RequestDate date
,@SwimmerTeamRequestID int
,@TeamSeasonID int
,@UserSwimmerID int

as

	if @ApprovalUserID = 0 set @ApprovalUserID = null

	declare @InsertedPrimaryKeyTable table (SwimmerTeamRequestID int)
		
	if exists (select 1 from dbo.SwimmerTeamRequest where SwimmerTeamRequestID = @SwimmerTeamRequestID)
		begin
			
			update dbo.SwimmerTeamRequest
			set
				 ApprovalDate = @ApprovalDate
				,ApprovalUserID = @ApprovalUserID
				,IsApproved = @IsApproved
				,RequestDate = @RequestDate
				,TeamSeasonID = @TeamSeasonID
				,UserSwimmerID = @UserSwimmerID
			output inserted.SwimmerTeamRequestID into @InsertedPrimaryKeyTable
			where SwimmerTeamRequestID = @SwimmerTeamRequestID
		end
	--prevent duplicates
	if exists(select 1 from dbo.SwimmerTeamRequest where TeamSeasonID = @TeamSeasonID and UserSwimmerID = @UserSwimmerID)
		begin
			insert into @InsertedPrimaryKeyTable
			select SwimmerTeamRequestID from dbo.SwimmerTeamRequest where TeamSeasonID = @TeamSeasonID and UserSwimmerID = @UserSwimmerID
		end
	else
		begin
			insert into dbo.SwimmerTeamRequest(
				 ApprovalDate
				,ApprovalUserID
				,IsApproved
				,RequestDate
				,TeamSeasonID
				,UserSwimmerID
			)
			output inserted.SwimmerTeamRequestID into @InsertedPrimaryKeyTable
			values (
				 @ApprovalDate
				,@ApprovalUserID
				,@IsApproved
				,@RequestDate
				,@TeamSeasonID
				,@UserSwimmerID
			)
			
		end

	select SwimmerTeamRequestID from @InsertedPrimaryKeyTable
		
go

