
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamGetByTeamSeasonID')
	begin
	    drop procedure dbo.usp_TeamGetByTeamSeasonID
	end
go

create procedure dbo.usp_TeamGetByTeamSeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamGetByTeamSeasonID
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/23/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
   HomeLocationID < System.Int32 >
 ********************************************************************************************************/
 @TeamSeasonID int

as
	select
		 t.TeamID
		,t.TeamName
		,t.Abbrev
		,t.HomePoolConfigID
		,s.Description as SeasonDescription
	from dbo.Team t
	inner join dbo.TeamSeason ts on ts.TeamID = t.TeamID
	inner join dbo.Season s on s.SeasonID = ts.SeasonID
	where ts.TeamSeasonID = @TeamSeasonID
		
go

