
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamGet')
	begin
	    drop procedure dbo.usp_TeamGet
	end
go

create procedure dbo.usp_TeamGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamGet
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/19/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
 ********************************************************************************************************/
 @TeamID int

as
	select
		 TeamID
		,TeamName
		,Abbrev
	from dbo.Team
	where
		TeamID = @TeamID
		
go

