
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetTeamGet')
	begin
	    drop procedure dbo.usp_HeatSheetTeamGet
	end
go

create procedure dbo.usp_HeatSheetTeamGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetTeamGet
 
 Description:		Selects a HeatSheetTeam record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/6/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the HeatSheetTeam Entity
 The Entity expects the following properties to be returned:
   HeatSheetID < System.Int32 >
   HeatSheetTeamID < System.Int32 >
   Lanes < System.String >
   TeamID < System.Int32 >
 ********************************************************************************************************/
 @HeatSheetTeamID int

as
	select
		 HeatSheetID
		,HeatSheetTeamID
		,Lanes
		,TeamSeasonID
	from dbo.HeatSheetTeam
	where HeatSheetTeamID = @HeatSheetTeamID
		
go

