
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamGetAllBySeasonID')
	begin
	    drop procedure dbo.usp_TeamGetAllBySeasonID
	end
go

create procedure dbo.usp_TeamGetAllBySeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamGetAllBySeasonID
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/18/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
 ********************************************************************************************************/
 @SeasonID int

as
	select
		 t.TeamID
		,t.TeamName
		,t.Abbrev
		,t.HomePoolConfigID
		,l.Name as LocationName
		,l.[Address]
		,l.PostalCode
		,ts.TeamSeasonID
	from dbo.Team t
	inner join dbo.TeamSeason ts on ts.TeamID = t.TeamID
	inner join dbo.PoolConfig pc on pc.PoolConfigID = t.HomePoolConfigID
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.Location l on l.LocationID = p.LocationID
	where ts.SeasonID = @SeasonID
		
go

