if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetSave')
	begin
	    drop procedure dbo.usp_SwimMeetSave
	end
go

create procedure dbo.usp_SwimMeetSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetSave

 Description:		Saves an SwimMeet record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @Description varchar(250)
,@EndDate datetime
,@LocationID int
,@SeasonID int
,@StartDate datetime
,@SwimMeetID int
,@SwimMeetTypeID int

as
	declare @InsertedPrimaryKeyTable table (SwimMeetID int)
		
	if exists (select 1 from dbo.SwimMeet where SwimMeetID = @SwimMeetID)
		begin
			
			update dbo.SwimMeet
			set
				 Description = @Description
				,EndDate = @EndDate
				,LocationID = @LocationID
				,SeasonID = @SeasonID
				,StartDate = @StartDate
				,SwimMeetTypeID = @SwimMeetTypeID
			output inserted.SwimMeetID into @InsertedPrimaryKeyTable
			where SwimMeetID = @SwimMeetID
		end
	else
		begin
			insert into dbo.SwimMeet(
				 Description
				,EndDate
				,LocationID
				,SeasonID
				,StartDate
				,SwimMeetTypeID
			)
			output inserted.SwimMeetID into @InsertedPrimaryKeyTable
			values (
				 @Description
				,@EndDate
				,@LocationID
				,@SeasonID
				,@StartDate
				,@SwimMeetTypeID
			)
			
		end

	select SwimMeetID from @InsertedPrimaryKeyTable
		
go

