
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerTeamRequestGetAllByTeamSeasonID')
	begin
	    drop procedure dbo.usp_SwimmerTeamRequestGetAllByTeamSeasonID
	end
go

create procedure dbo.usp_SwimmerTeamRequestGetAllByTeamSeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerTeamRequestGetAllByTeamSeasonID
 
 Description:		Selects a Swimmer records having unapproved requests for the given TeamSeason
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/18/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Swimmer Entity
 The Entity expects the following properties to be returned:
   BirthDate < System.DateTime >
   FirstName < System.String >
   LastName < System.String >
   SwimmerID < System.Int32 >
   IsMale < System.Boolean >
 ********************************************************************************************************/
 @TeamSeasonID int

as
	select
		 s.BirthDate
		,s.FirstName
		,s.LastName
		,s.SwimmerID
		,s.IsMale
		,strq.TeamSeasonID
		,strq.SwimmerTeamRequestID
	from dbo.Swimmer s
	inner join dbo.UserSwimmer us on us.SwimmerID = s.SwimmerID
	inner join dbo.SwimmerTeamRequest strq on strq.UserSwimmerID = us.UserSwimmerID
	where strq.TeamSeasonID = @TeamSeasonID
	and strq.IsApproved  = 0
	order by s.LastName
			,s.FirstName

go

