
if exists (select * from sysobjects where type = 'P' and name = 'usp_LocationGetAllBySystemUserID')
	begin
	    drop procedure dbo.usp_LocationGetAllBySystemUserID
	end
go

create procedure dbo.usp_LocationGetAllBySystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LocationGetAllBySystemUserID
 
 Description:		Selects a UserLocation record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/29/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the UserLocation Entity
 The Entity expects the following properties to be returned:
   LocationID < System.Int32 >
   SystemUserID < System.Int32 >
   UserLocationID < System.Int32 >
 ********************************************************************************************************/
 @SystemUserID int

as
	select
		 ul.SystemUserID
		,ul.UserLocationID
		,l.[Address]
		,l.City
		,l.CreatedByUserID
		,l.CreatedDate
		,l.Latitude
		,l.LocationID
		,l.Longitude
		,l.ModifiedByUserID
		,l.ModifiedDate
		,l.Name
		,l.PostalCode
		,l.RegionID
		,r.RegionAbbrev
		,COUNT(p.PoolID) as PoolCount
	from dbo.UserLocation ul
	inner join dbo.Location l on l.LocationID = ul.LocationID
	inner join dbo.Region r on r.RegionID = l.RegionID
	inner join dbo.[Pool] p on p.LocationID = l.LocationID
	where ul.SystemUserID = @SystemUserID
	group by ul.SystemUserID
			,ul.UserLocationID
			,l.[Address]
			,l.City
			,l.CreatedByUserID
			,l.CreatedDate
			,l.Latitude
			,l.LocationID
			,l.Longitude
			,l.ModifiedByUserID
			,l.ModifiedDate
			,l.Name
			,l.PostalCode
			,l.RegionID
			,r.RegionAbbrev
		
go

