
if exists (select * from sysobjects where type = 'P' and name = 'usp_RegionGet')
	begin
	    drop procedure dbo.usp_RegionGet
	end
go

create procedure dbo.usp_RegionGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_RegionGet
 
 Description:		Selects a Region record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/29/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Region Entity
 The Entity expects the following properties to be returned:
   RegionAbbrev < System.String >
   RegionID < System.Int32 >
   RegionName < System.String >
 ********************************************************************************************************/
 @RegionID int

as
	select
		 RegionAbbrev
		,RegionID
		,RegionName
	from dbo.Region
	where
		RegionID = @RegionID
		
go

