if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetTeamSave')
	begin
	    drop procedure dbo.usp_SwimMeetTeamSave
	end
go

create procedure dbo.usp_SwimMeetTeamSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetTeamSave

 Description:		Saves an SwimMeetTeam record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @IsHomeTeam bit
,@SwimMeetID int
,@SwimMeetTeamID int
,@TeamSeasonID int

as
	declare @InsertedPrimaryKeyTable table (SwimMeetTeamID int)
		
	if exists (select 1 from dbo.SwimMeetTeam where SwimMeetTeamID = @SwimMeetTeamID)
		begin
			
			update dbo.SwimMeetTeam
			set
				 IsHomeTeam = @IsHomeTeam
				,SwimMeetID = @SwimMeetID
				,TeamSeasonID = @TeamSeasonID
			output inserted.SwimMeetTeamID into @InsertedPrimaryKeyTable
			where SwimMeetTeamID = @SwimMeetTeamID
		end
	--prevent duplicates
	if exists(select 1 from dbo.SwimMeetTeam where TeamSeasonID = @TeamSeasonID and SwimMeetID = @SwimMeetID)
		begin

			update dbo.SwimMeetTeam
			set IsHomeTeam = @IsHomeTeam
			where TeamSeasonID = @TeamSeasonID 
			and SwimMeetID = @SwimMeetID

			insert into @InsertedPrimaryKeyTable
			select SwimMeetTeamID from dbo.SwimMeetTeam where TeamSeasonID = @TeamSeasonID and SwimMeetID = @SwimMeetID
		end
	else
		begin
			insert into dbo.SwimMeetTeam(
				 IsHomeTeam
				,SwimMeetID
				,TeamSeasonID
			)
			output inserted.SwimMeetTeamID into @InsertedPrimaryKeyTable
			values (
				 @IsHomeTeam
				,@SwimMeetID
				,@TeamSeasonID
			)
			
		end

	select SwimMeetTeamID from @InsertedPrimaryKeyTable
		
go

