
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSwimmerGetAllByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_HeatSwimmerGetAllByHeatSheetEventID
	end
go

create procedure dbo.usp_HeatSwimmerGetAllByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSwimmerGetAllByHeatSheetEventID
 
 Description:		Selects a HeatSwimmer record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/20/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the HeatSwimmer Entity
 The Entity expects the following properties to be returned:
   LaneNumber < System.Int32 >
   HeatID < System.Int32 >
   HeatSwimmerID < System.Int32 >
   SwimmerID < System.Int32 >
   Leg < System.Int32 >
   SeedResultID < System.Int32 >
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	select
		 hs.HeatID
		,hs.HeatSwimmerID
		,hs.LaneNumber
		,hs.Leg
		,hs.SeedResultID
		,hs.SwimmerTeamSeasonID
	from dbo.HeatSwimmer hs
	inner join dbo.Heat h on h.HeatID = hs.HeatID
	where h.HeatSheetEventID = @HeatSheetEventID
	order by hs.HeatID
			,hs.LaneNumber
			,hs.Leg
go

