if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetTeamSave')
	begin
	    drop procedure dbo.usp_HeatSheetTeamSave
	end
go

create procedure dbo.usp_HeatSheetTeamSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetTeamSave

 Description:		Saves an HeatSheetTeam record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/6/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetID int
,@HeatSheetTeamID int
,@Lanes varchar(50)
,@TeamSeasonID int

as
	declare @InsertedPrimaryKeyTable table (HeatSheetTeamID int)
		
	if exists (select 1 from dbo.HeatSheetTeam where HeatSheetTeamID = @HeatSheetTeamID)
		begin
			
			update dbo.HeatSheetTeam
			set
				 HeatSheetID = @HeatSheetID
				,Lanes = @Lanes
				,TeamSeasonID = @TeamSeasonID
			output inserted.HeatSheetTeamID into @InsertedPrimaryKeyTable
			where HeatSheetTeamID = @HeatSheetTeamID
		end
	--prevent duplicates
	if exists(select 1 from dbo.HeatSheetTeam where HeatSheetID = @HeatSheetID and TeamSeasonID = @TeamSeasonID)
		begin
			update dbo.HeatSheetTeam
			set Lanes = @Lanes
			where HeatSheetID = @HeatSheetID 
			and TeamSeasonID = @TeamSeasonID

			insert into @InsertedPrimaryKeyTable
			select HeatSheetTeamID from dbo.HeatSheetTeam where HeatSheetID = @HeatSheetID and TeamSeasonID = @TeamSeasonID
		end
	else
		begin
			insert into dbo.HeatSheetTeam(
				 HeatSheetID
				,Lanes
				,TeamSeasonID
			)
			output inserted.HeatSheetTeamID into @InsertedPrimaryKeyTable
			values (
				 @HeatSheetID
				,@Lanes
				,@TeamSeasonID
			)
			
		end

	select HeatSheetTeamID from @InsertedPrimaryKeyTable
		
go

