if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonSave')
	begin
	    drop procedure dbo.usp_SeasonSave
	end
go

create procedure dbo.usp_SeasonSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonSave

 Description:		Saves an Season record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/14/2011	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @AgeClassRuleCustomDate datetime
,@AgeClassRuleID int
,@Description varchar(250)
,@EndDate datetime
,@LeagueID int
,@SeasonID int
,@StartDate datetime

as
	declare @InsertedPrimaryKeyTable table (SeasonID int)
		
	if exists (select 1 from dbo.Season where SeasonID = @SeasonID)
		begin
			
			update dbo.Season
			set
				 AgeClassRuleCustomDate = @AgeClassRuleCustomDate
				,AgeClassRuleID = @AgeClassRuleID
				,Description = @Description
				,EndDate = @EndDate
				,LeagueID = @LeagueID
				,StartDate = @StartDate
			output inserted.SeasonID into @InsertedPrimaryKeyTable
			where SeasonID = @SeasonID
		end
	else
		begin
			insert into dbo.Season(
				 AgeClassRuleCustomDate
				,AgeClassRuleID
				,Description
				,EndDate
				,LeagueID
				,StartDate
			)
			output inserted.SeasonID into @InsertedPrimaryKeyTable
			values (
				 @AgeClassRuleCustomDate
				,@AgeClassRuleID
				,@Description
				,@EndDate
				,@LeagueID
				,@StartDate
			)
			
		end

	select SeasonID from @InsertedPrimaryKeyTable
		
go

