
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerTeamSeasonGetAllBySwimmerID')
	begin
	    drop procedure dbo.usp_SwimmerTeamSeasonGetAllBySwimmerID
	end
go

create procedure dbo.usp_SwimmerTeamSeasonGetAllBySwimmerID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerTeamSeasonGetAllBySwimmerID
 
 Description:		Selects a SwimmerTeamSeason record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/21/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimmerTeamSeason Entity
 The Entity expects the following properties to be returned:
   EndDate < System.DateTime >
   StartDate < System.DateTime >
   SwimmerID < System.Int32 >
   SwimmerTeamSeasonID < System.Int32 >
   TeamSeasonID < System.Int32 >
 ********************************************************************************************************/
 @SwimmerID int

as
	select
		 sts.EndDate
		,sts.StartDate
		,sts.SwimmerID
		,sts.SwimmerTeamSeasonID
		,sts.TeamSeasonID
		,ts.TeamID
	from dbo.SwimmerTeamSeason sts
	inner join dbo.TeamSeason ts on ts.TeamSeasonID = sts.TeamSeasonID
	where sts.SwimmerID = @SwimmerID
		
go

