if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamLeagueRequestSave')
	begin
	    drop procedure dbo.usp_TeamLeagueRequestSave
	end
go

create procedure dbo.usp_TeamLeagueRequestSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamLeagueRequestSave

 Description:		Saves an TeamLeagueRequest record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/8/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @ApprovalDate date
,@ApprovalUserID int
,@IsApproved bit
,@RequestDate date
,@SeasonID int
,@TeamLeagueRequestID int
,@UserTeamID int

as
	if @ApprovalUserID = 0 set @ApprovalUserID = null

	declare @InsertedPrimaryKeyTable table (TeamLeagueRequestID int)
		
	if exists (select 1 from dbo.TeamLeagueRequest where TeamLeagueRequestID = @TeamLeagueRequestID)
		begin
			
			update dbo.TeamLeagueRequest
			set
				 ApprovalDate = @ApprovalDate
				,ApprovalUserID = @ApprovalUserID
				,IsApproved = @IsApproved
				,RequestDate = @RequestDate
				,SeasonID = @SeasonID
				,UserTeamID = @UserTeamID
			output inserted.TeamLeagueRequestID into @InsertedPrimaryKeyTable
			where TeamLeagueRequestID = @TeamLeagueRequestID
		end
	--prevent duplicates
	if exists(select 1 from dbo.TeamLeagueRequest where SeasonID = @SeasonID and UserTeamID = @UserTeamID)
		begin
			insert into @InsertedPrimaryKeyTable
			select TeamLeagueRequestID from dbo.TeamLeagueRequest where SeasonID = @SeasonID and UserTeamID = @UserTeamID
		end
	else
		begin
			insert into dbo.TeamLeagueRequest(
				 ApprovalDate
				,ApprovalUserID
				,IsApproved
				,RequestDate
				,SeasonID
				,UserTeamID
			)
			output inserted.TeamLeagueRequestID into @InsertedPrimaryKeyTable
			values (
				 @ApprovalDate
				,@ApprovalUserID
				,@IsApproved
				,@RequestDate
				,@SeasonID
				,@UserTeamID
			)
			
		end

	select TeamLeagueRequestID from @InsertedPrimaryKeyTable
		
go

