
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetEventGetAllByHeatSheetID')
	begin
	    drop procedure dbo.usp_HeatSheetEventGetAllByHeatSheetID
	end
go

create procedure dbo.usp_HeatSheetEventGetAllByHeatSheetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetEventGetAllByHeatSheetID
 
 Description:		Selects a HeatSheetEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/7/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the HeatSheetEvent Entity
 The Entity expects the following properties to be returned:
   Sequence < System.Int32 >
   SwimEventID < System.Int32 >
   HeatSheetEventID < System.Int32 >
   Distance < System.Int32 >
   HeatSheetID < System.Int32 >
 ********************************************************************************************************/
 @HeatSheetID int

as
	select
		 hse.[Sequence]
		,hse.SwimEventID
		,hse.HeatSheetEventID
		,hse.Distance
		,hse.HeatSheetID
		,ac.[Description] + ' ' + cast(hse.Distance as varchar) + ' ' + substring(u.[Description],0,LEN(u.[Description])) + ' ' + s.[Description] as [Description]
	from dbo.HeatSheetEvent hse
	inner join dbo.SwimEvent se on se.SwimEventID = hse.SwimEventID
	inner join dbo.AgeClass ac on ac.AgeClassID = se.AgeClassID
	inner join dbo.Stroke s on s.StrokeID = se.StrokeID
	inner join dbo.HeatSheet hs on hs.HeatSheetID = hse.HeatSheetID
	inner join dbo.PoolConfig pc on pc.PoolConfigID = hs.PoolConfigID
	inner join dbo.UOM u on u.UOMID = pc.UOMID
	where hse.HeatSheetID = @HeatSheetID
	order by [Sequence]
		
go

