
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSwimmerDelete')
	begin
	    drop procedure dbo.usp_HeatSwimmerDelete
	end
go

create procedure dbo.usp_HeatSwimmerDelete
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 -------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSwimmerDelete
 
 Description:		Deletes a HeatSwimmer record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSwimmerID int

as
	delete
	from dbo.HeatSwimmer
	where
		HeatSwimmerID = @HeatSwimmerID

go

