
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_SeasonGetByHeatSheetEventID
	end
go

create procedure dbo.usp_SeasonGetByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetByHeatSheetEventID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/22/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
	from dbo.Season s
	inner join dbo.SwimMeet sm on sm.SeasonID = s.SeasonID
	inner join dbo.HeatSheet hs on hs.SwimMeetID = sm.SwimMeetID
	inner join dbo.HeatSheetEvent hse on hse.HeatSheetID = hs.HeatSheetID
	where hse.HeatSheetEventID = @HeatSheetEventID
		
go

