
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetByHeatID')
	begin
	    drop procedure dbo.usp_PoolConfigGetByHeatID
	end
go

create procedure dbo.usp_PoolConfigGetByHeatID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetByHeatID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatID int

as
	select	 pc.CreatedByUserID
			,pc.CreatedDate
			,pc.[Description]
			,pc.LaneCount
			,pc.LaneLength
			,pc.ModifiedByUserID
			,pc.ModifiedDate
			,pc.PoolConfigID
			,pc.PoolID
			,pc.UOMID
	from dbo.PoolConfig pc
	inner join dbo.HeatSheet hs on hs.PoolConfigID = pc.PoolConfigID
	inner join dbo.HeatSheetEvent hse on hse.HeatSheetID = hs.HeatSheetID
	inner join dbo.Heat h on h.HeatSheetEventID = hse.HeatSheetEventID
	where h.HeatID = @HeatID
		
go

