
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetAllCurrentByLeagueID')
	begin
	    drop procedure dbo.usp_SeasonGetAllCurrentByLeagueID
	end
go

create procedure dbo.usp_SeasonGetAllCurrentByLeagueID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetAllCurrentByLeagueID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/17/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
 ********************************************************************************************************/
 @LeagueID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
	from dbo.Season s
	where s.LeagueID = @LeagueID
	and s.EndDate >= GETDATE()
		
go

