
if exists (select * from sysobjects where type = 'P' and name = 'usp_ScoreGetTotalBySwimMeetID')
	begin
	    drop procedure dbo.usp_ScoreGetTotalBySwimMeetID
	end
go

create procedure dbo.usp_ScoreGetTotalBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ScoreGetTotalBySwimMeetID
 
 Description:		Selects a Score record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 2/12/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Score Entity
 The Entity expects the following properties to be returned:
   SwimMeetID < System.Int32 >
   Disqualified < System.Boolean >
   TeamID < System.Int32 >
   ElapsedTime < System.Double >
   Swimmer < System.String >
   LaneLength < System.Double >
   Abbrev < System.String >
   Description < System.String >
   SwimmerID < System.Int32 >
   IsRelay < System.Boolean >
   EventDate < System.DateTime >
   Split < System.Double >
   IsCertified < System.Boolean >
   IsProtested < System.Boolean >
   Place < System.Int32 >
   Points < System.Double >
 ********************************************************************************************************/
 @SwimMeetID int

as

	declare @Score table(TeamID int
						,Abbrev varchar(5)
						,Points decimal(14,4))

	--Get Individual Event Scores
	insert into @Score (TeamID,Abbrev,Points)
	select
		 TeamID
		,Abbrev
		,sum(Points) as Points
	from dbo.vwScore
	where SwimMeetID = @SwimMeetID
	and IsRelay = 0
	group by TeamID
			,Abbrev

	--Get Relay Event Scores
	insert into @Score (TeamID,Abbrev,Points)
	select
		 TeamID
		,Abbrev
		,sum(Points/4) as Points
	from dbo.vwScore
	where SwimMeetID = @SwimMeetID
	and IsRelay = 1
	group by TeamID
			,Abbrev

	select
		 TeamID
		,Abbrev
		,sum(Points) as Points
	from @Score
	group by TeamID
			,Abbrev
	order by Abbrev
go

