
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSwimmerGetByLaneNumberHeatID')
	begin
	    drop procedure dbo.usp_HeatSwimmerGetByLaneNumberHeatID
	end
go

create procedure dbo.usp_HeatSwimmerGetByLaneNumberHeatID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSwimmerGetByLaneNumberHeatID
 
 Description:		Selects a HeatSwimmer record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 7/19/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the HeatSwimmer Entity
 The Entity expects the following properties to be returned:
   LaneNumber < System.Int32 >
   Disqualified < System.Boolean >
   ElapsedTime < System.Double >
   HeatID < System.Int32 >
   HeatSwimmerID < System.Int32 >
   SwimmerID < System.Int32 >
   Leg < System.Int32 >
 ********************************************************************************************************/
 @LaneNumber int
,@HeatID int

as
	select
		 HeatID
		,HeatSwimmerID
		,LaneNumber
		,SeedResultID
		,SwimmerTeamSeasonID
		,Leg
	from dbo.HeatSwimmer
	where LaneNumber = @LaneNumber
	and	HeatID = @HeatID
		
go

