
if exists (select * from sysobjects where type = 'P' and name = 'usp_AgeClassGetAll')
	begin
	    drop procedure dbo.usp_AgeClassGetAll
	end
go

create procedure dbo.usp_AgeClassGetAll
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_AgeClassGetAll
 
 Description:		Selects a AgeClass record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/3/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the AgeClass Entity
 The Entity expects the following properties to be returned:
   AgeClassID < System.Int32 >
   Description < System.String >
 ********************************************************************************************************/

as
	select
		 AgeClassID
		,Description
		,IsMale
		,MinAge
		,MaxAge
	from dbo.AgeClass
	order by IsMale, MaxAge
		
go

