
if exists (select * from sysobjects where type = 'P' and name = 'usp_LocationGetBySwimMeetID')
	begin
	    drop procedure dbo.usp_LocationGetBySwimMeetID
	end
go

create procedure dbo.usp_LocationGetBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LocationGetBySwimMeetID
 
 Description:		Selects a Location record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Location Entity
 The Entity expects the following properties to be returned:
   Address < System.String >
   City < System.String >
   LocationID < System.Int32 >
   Name < System.String >
   PostalCode < System.String >
   RegionID < System.Int32 >
 ********************************************************************************************************/
 @SwimMeetID int

as
	select
		 l.[Address]
		,l.City
		,l.Latitude
		,l.LocationID
		,l.Longitude
		,l.Name
		,l.PostalCode
		,l.RegionID
	from dbo.Location l
	inner join dbo.SwimMeet sm on sm.LocationID = l.LocationID
	where sm.SwimMeetID = @SwimMeetID
		
go

