if exists (select * from sysobjects where type = 'P' and name = 'usp_UserTeamSave')
	begin
	    drop procedure dbo.usp_UserTeamSave
	end
go

create procedure dbo.usp_UserTeamSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserTeamSave

 Description:		Saves an UserTeam record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/8/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SystemUserID int
,@TeamID int
,@UserTeamID int

as
	declare @InsertedPrimaryKeyTable table (UserTeamID int)
		
	if exists (select 1 from dbo.UserTeam where UserTeamID = @UserTeamID)
		begin
			
			update dbo.UserTeam
			set
				 SystemUserID = @SystemUserID
				,TeamID = @TeamID
			output inserted.UserTeamID into @InsertedPrimaryKeyTable
			where UserTeamID = @UserTeamID
		end
	--prevent duplicates
	if exists(select 1 from dbo.UserTeam where SystemUserID = @SystemUserID and TeamID = @TeamID)
		begin
			insert into @InsertedPrimaryKeyTable
			select UserTeamID from dbo.UserTeam where SystemUserID = @SystemUserID and TeamID = @TeamID
		end
	else
		begin
			insert into dbo.UserTeam(
				 SystemUserID
				,TeamID
			)
			output inserted.UserTeamID into @InsertedPrimaryKeyTable
			values (
				 @SystemUserID
				,@TeamID
			)
			
		end

	select UserTeamID from @InsertedPrimaryKeyTable
		
go

