
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamGetByUserTeamID')
	begin
	    drop procedure dbo.usp_TeamGetByUserTeamID
	end
go

create procedure dbo.usp_TeamGetByUserTeamID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamGetByUserTeamID
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/20/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
   HomeLocationID < System.Int32 >
 ********************************************************************************************************/
 @UserTeamID int

as
	select
		 t.TeamID
		,t.TeamName
		,t.Abbrev
		,t.HomePoolConfigID
		,ut.UserTeamID
	from dbo.Team t
	inner join dbo.UserTeam ut on ut.TeamID = t.TeamID
	where ut.UserTeamID = @UserTeamID
		
go

