if exists (select * from sysobjects where type = 'P' and name = 'usp_UserSwimmerSave')
	begin
	    drop procedure dbo.usp_UserSwimmerSave
	end
go

create procedure dbo.usp_UserSwimmerSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserSwimmerSave

 Description:		Saves an UserSwimmer record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/9/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimmerID int
,@SystemUserID int
,@UserSwimmerID int

as
	declare @InsertedPrimaryKeyTable table (UserSwimmerID int)
		
	if exists (select 1 from dbo.UserSwimmer where UserSwimmerID = @UserSwimmerID)
		begin
			
			update dbo.UserSwimmer
			set
				 SwimmerID = @SwimmerID
				,SystemUserID = @SystemUserID
			output inserted.UserSwimmerID into @InsertedPrimaryKeyTable
			where UserSwimmerID = @UserSwimmerID
		end
	--prevent duplicates
	if exists(select 1 from dbo.UserSwimmer where SystemUserID = @SystemUserID and SwimmerID = @SwimmerID)
		begin
			insert into @InsertedPrimaryKeyTable
			select UserSwimmerID from dbo.UserSwimmer where SystemUserID = @SystemUserID and SwimmerID = @SwimmerID
		end
	else
		begin
			insert into dbo.UserSwimmer(
				 SwimmerID
				,SystemUserID
			)
			output inserted.UserSwimmerID into @InsertedPrimaryKeyTable
			values (
				 @SwimmerID
				,@SystemUserID
			)
			
		end

	select UserSwimmerID from @InsertedPrimaryKeyTable
		
go

