
if exists (select * from sysobjects where type = 'P' and name = 'usp_StrokeGetAll')
	begin
	    drop procedure dbo.usp_StrokeGetAll
	end
go

create procedure dbo.usp_StrokeGetAll
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_StrokeGetAll
 
 Description:		Selects a Stroke record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/3/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/

as
	select
		 Description
		,IsRelay
		,StrokeID
	from dbo.Stroke
	order by Description
		
go

