
if exists (select * from sysobjects where type = 'P' and name = 'usp_LeagueGet')
	begin
	    drop procedure dbo.usp_LeagueGet
	end
go

create procedure dbo.usp_LeagueGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LeagueGet
 
 Description:		Selects a League record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 7/15/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @LeagueID int

as
	select
		 [Description]
		,LeagueID
		,LeagueName
		,RegionID
	from dbo.League
	where LeagueID = @LeagueID
		
go

