if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamSeasonSave')
	begin
	    drop procedure dbo.usp_TeamSeasonSave
	end
go

create procedure dbo.usp_TeamSeasonSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamSeasonSave

 Description:		Saves an TeamSeason record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @AgeClassRuleID int
,@LeagueID int
,@SeasonID int
,@TeamID int
,@TeamSeasonID int

as
	declare @InsertedPrimaryKeyTable table (TeamSeasonID int)
		
	if exists (select 1 from dbo.TeamSeason where TeamSeasonID = @TeamSeasonID)
		begin
			
			update dbo.TeamSeason
			set
				 AgeClassRuleID = @AgeClassRuleID
				,LeagueID = @LeagueID
				,SeasonID = @SeasonID
				,TeamID = @TeamID
			output inserted.TeamSeasonID into @InsertedPrimaryKeyTable
			where TeamSeasonID = @TeamSeasonID
		end
	--prevent duplicates
	if exists(select 1 from dbo.TeamSeason where SeasonID = @SeasonID and TeamID = @TeamID)
		begin
			update dbo.TeamSeason
			set
				 AgeClassRuleID = @AgeClassRuleID
				,LeagueID = @LeagueID
			where SeasonID = @SeasonID 
			and TeamID = @TeamID
			
			insert into @InsertedPrimaryKeyTable
			select TeamSeasonID from dbo.TeamSeason where SeasonID = @SeasonID and TeamID = @TeamID
		end
	else
		begin
			insert into dbo.TeamSeason(
				 AgeClassRuleID
				,LeagueID
				,SeasonID
				,TeamID
			)
			output inserted.TeamSeasonID into @InsertedPrimaryKeyTable
			values (
				 @AgeClassRuleID
				,@LeagueID
				,@SeasonID
				,@TeamID
			)
			
		end

	select TeamSeasonID from @InsertedPrimaryKeyTable
		
go

