
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatGetAllByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_HeatGetAllByHeatSheetEventID
	end
go

create procedure dbo.usp_HeatGetAllByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatGetAllByHeatSheetEventID
 
 Description:		Selects a Heat record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/7/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Heat Entity
 The Entity expects the following properties to be returned:
   HeatID < System.Int32 >
   HeatNumber < System.Int32 >
   HeatSheetEventID < System.Int32 >
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	select
		 HeatID
		,HeatNumber
		,HeatSheetEventID
	from dbo.Heat
	where HeatSheetEventID = @HeatSheetEventID
	order by HeatNumber
		
go

