
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonScoringSchemeDeleteBySeasonID')
	begin
	    drop procedure dbo.usp_SeasonScoringSchemeDeleteBySeasonID
	end
go

create procedure dbo.usp_SeasonScoringSchemeDeleteBySeasonID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonScoringSchemeDeleteBySeasonID
 
 Description:		Selects a SeasonScoringScheme record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/14/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SeasonScoringScheme Entity
 The Entity expects the following properties to be returned:
   ScoringSchemeID < System.Int32 >
   SeasonID < System.Int32 >
   SeasonScoringSchemeID < System.Int32 >
 ********************************************************************************************************/
 @SeasonID int

as
	delete dbo.SeasonScoringScheme
	where SeasonID = @SeasonID
		
go

