
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetGetAll')
	begin
	    drop procedure dbo.usp_SwimMeetGetAll
	end
go

create procedure dbo.usp_SwimMeetGetAll
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetGetAll
 
 Description:		Selects a SwimMeet record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/3/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the SwimMeet Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   LocationID < System.Int32 >
   StartDate < System.DateTime >
   SwimMeetID < System.Int32 >
 ********************************************************************************************************/

as
	select
		 Description
		,EndDate
		,LocationID
		,SeasonID
		,StartDate
		,SwimMeetID
		,SwimMeetTypeID
	from dbo.SwimMeet
		
go

