
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamLeagueRequestGet')
	begin
	    drop procedure dbo.usp_TeamLeagueRequestGet
	end
go

create procedure dbo.usp_TeamLeagueRequestGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamLeagueRequestGet
 
 Description:		Selects a TeamLeagueRequest record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/21/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the TeamLeagueRequest Entity
 The Entity expects the following properties to be returned:
   ApprovalDate < System.DateTime >
   ApprovalUserID < System.Int32 >
   IsApproved < System.Boolean >
   RequestDate < System.DateTime >
   SeasonID < System.Int32 >
   TeamLeagueRequestID < System.Int32 >
   UserTeamID < System.Int32 >
 ********************************************************************************************************/
 @TeamLeagueRequestID int

as
	select
		 ApprovalDate
		,ApprovalUserID
		,IsApproved
		,RequestDate
		,SeasonID
		,TeamLeagueRequestID
		,UserTeamID
	from dbo.TeamLeagueRequest
	where
		TeamLeagueRequestID = @TeamLeagueRequestID
		
go

