
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatGetByHeatSwimmerID')
	begin
	    drop procedure dbo.usp_HeatGetByHeatSwimmerID
	end
go

create procedure dbo.usp_HeatGetByHeatSwimmerID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatGetByHeatSwimmerID
 
 Description:		Selects a Heat record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/20/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSwimmerID int

as
	select
		 h.HeatID
		,h.HeatNumber
		,h.HeatSheetEventID
	from dbo.Heat h
	inner join dbo.HeatSwimmer hs on hs.HeatID = h.HeatID
	where hs.HeatSwimmerID = @HeatSwimmerID
		
go

