if exists (select * from sysobjects where type = 'P' and name = 'usp_SystemUserSave')
	begin
	    drop procedure dbo.usp_SystemUserSave
	end
go

create procedure dbo.usp_SystemUserSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SystemUserSave

 Description:		Saves an SystemUser record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/10/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @CreateDate datetime
,@City varchar(50)
,@Email varchar(250)
,@FirstName varchar(50)
,@IsActive bit
,@LastName varchar(50)
,@ModifiedDate datetime
,@Password varchar(250)
,@RegionID int
,@RegistrationKey uniqueidentifier
,@ResetPassword bit
,@SystemUserID int
,@TemporaryPassword varchar(50)
,@UserName varchar(50)

as
	declare @InsertedPrimaryKeyTable table (SystemUserID int)
		
	if exists (select 1 from dbo.SystemUser where SystemUserID = @SystemUserID)
		begin
			
			update dbo.SystemUser
			set
				 CreateDate = @CreateDate
				,City = @City
				,Email = @Email
				,FirstName = @FirstName
				,IsActive = @IsActive
				,LastName = @LastName
				,ModifiedDate = @ModifiedDate
				,[Password] = @Password
				,RegionID = @RegionID
				,RegistrationKey = @RegistrationKey
				,ResetPassword = @ResetPassword
				,TemporaryPassword = @TemporaryPassword
				,UserName = @UserName
			output inserted.SystemUserID into @InsertedPrimaryKeyTable
			where SystemUserID = @SystemUserID
		end
	else
		begin
			insert into dbo.SystemUser(
				 CreateDate
				,City
				,Email
				,FirstName
				,IsActive
				,LastName
				,ModifiedDate
				,[Password]
				,RegionID
				,RegistrationKey
				,ResetPassword
				,TemporaryPassword
				,UserName
			)
			output inserted.SystemUserID into @InsertedPrimaryKeyTable
			values (
				 @CreateDate
				,@City
				,@Email
				,@FirstName
				,@IsActive
				,@LastName
				,@ModifiedDate
				,@Password
				,@RegionID
				,@RegistrationKey
				,@ResetPassword
				,@TemporaryPassword
				,@UserName
			)
			
		end

	select SystemUserID from @InsertedPrimaryKeyTable
		
go

