if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigSave')
	begin
	    drop procedure dbo.usp_PoolConfigSave
	end
go

create procedure dbo.usp_PoolConfigSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigSave

 Description:		Saves an PoolConfig record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
	 @CreatedByUserID int
	,@CreatedDate datetime
	,@Description varchar(50)
	,@LaneCount int
	,@LaneLength decimal(9,4)
	,@ModifiedByUserID int
	,@ModifiedDate datetime
	,@PoolConfigID int
	,@PoolID int
	,@UOMID int

as
	if @ModifiedByUserID = 0 set @ModifiedByUserID = null

	declare @InsertedPrimaryKeyTable table (PoolConfigID int)
		
	if exists (select 1 from dbo.PoolConfig where PoolConfigID = @PoolConfigID)
		begin
			
			update dbo.PoolConfig
			set  CreatedByUserID = @CreatedByUserID
				,CreatedDate = @CreatedDate
				,[Description] = @Description
				,LaneCount = @LaneCount
				,LaneLength = @LaneLength
				,ModifiedByUserID = @ModifiedByUserID
				,ModifiedDate = @ModifiedDate
				,PoolID = @PoolID
				,UOMID = @UOMID
			output inserted.PoolConfigID into @InsertedPrimaryKeyTable
			where PoolConfigID = @PoolConfigID
		end
	else
		begin
			insert into dbo.PoolConfig(
				  CreatedByUserID
				 ,CreatedDate
				 ,[Description]
				 ,LaneCount
				 ,LaneLength
				 ,ModifiedByUserID
				 ,ModifiedDate
				 ,PoolID
				 ,UOMID
			)
			output inserted.PoolConfigID into @InsertedPrimaryKeyTable
			values (
				  @CreatedByUserID
				 ,@CreatedDate
				 ,@Description
				 ,@LaneCount
				 ,@LaneLength
				 ,@ModifiedByUserID
				 ,@ModifiedDate
				 ,@PoolID
				 ,@UOMID
			)			
		end

	select PoolConfigID from @InsertedPrimaryKeyTable
		
go

