if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimmerTeamSeasonSave')
	begin
	    drop procedure dbo.usp_SwimmerTeamSeasonSave
	end
go

create procedure dbo.usp_SwimmerTeamSeasonSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimmerTeamSeasonSave

 Description:		Saves an SwimmerTeamSeason record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @EndDate smalldatetime
,@StartDate smalldatetime
,@SwimmerID int
,@SwimmerTeamSeasonID int
,@TeamSeasonID int

as
	declare @InsertedPrimaryKeyTable table (SwimmerTeamSeasonID int)
		
	if exists (select 1 from dbo.SwimmerTeamSeason where SwimmerTeamSeasonID = @SwimmerTeamSeasonID)
		begin
			
			update dbo.SwimmerTeamSeason
			set
				 EndDate = @EndDate
				,StartDate = @StartDate
				,SwimmerID = @SwimmerID
				,TeamSeasonID = @TeamSeasonID
			output inserted.SwimmerTeamSeasonID into @InsertedPrimaryKeyTable
			where SwimmerTeamSeasonID = @SwimmerTeamSeasonID
		end
	--prevent duplicates
	if exists(select 1 from dbo.SwimmerTeamSeason where SwimmerID = @SwimmerID and TeamSeasonID = @TeamSeasonID)
		begin
			update dbo.SwimmerTeamSeason
			set EndDate = @EndDate,
			StartDate = @StartDate
			where SwimmerID = @SwimmerID 
			and TeamSeasonID = @TeamSeasonID
			
			insert into @InsertedPrimaryKeyTable
			select SwimmerTeamSeasonID from dbo.SwimmerTeamSeason where SwimmerID = @SwimmerID and TeamSeasonID = @TeamSeasonID
		end
	else
		begin
			insert into dbo.SwimmerTeamSeason(
				 EndDate
				,StartDate
				,SwimmerID
				,TeamSeasonID
			)
			output inserted.SwimmerTeamSeasonID into @InsertedPrimaryKeyTable
			values (
				 @EndDate
				,@StartDate
				,@SwimmerID
				,@TeamSeasonID
			)
			
		end

	select SwimmerTeamSeasonID from @InsertedPrimaryKeyTable
		
go

