
if exists (select * from sysobjects where type = 'P' and name = 'usp_ScoreGetAllBySwimMeetIDSystemUserID')
	begin
	    drop procedure dbo.usp_ScoreGetAllBySwimMeetIDSystemUserID
	end
go

create procedure dbo.usp_ScoreGetAllBySwimMeetIDSystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ScoreGetAllBySwimMeetIDSystemUserID
 
 Description:		Selects a Score record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 4/4/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int
,@SystemUserID int

as

	--get all the HeatSheetEvents for this SystemUser and SwimMeet so the results for all swimmers in the events will be returned
	--instead of just the UserSwimmer's results
	declare @HeatSheetEvent table(HeatSheetEventID int)
	insert into @HeatSheetEvent
	select v.HeatSheetEventID 
	from dbo.vwScore v
	inner join dbo.UserSwimmer us on us.SwimmerID = v.SwimmerID
	where v.SwimMeetID = @SwimMeetID
	and us.SystemUserID = @SystemUserID
	group by v.HeatSheetEventID

	select
		 v.SwimMeetID
		,v.Disqualified
		,v.TeamID
		,v.ElapsedTime
		,v.Swimmer
		,v.LaneLength
		,v.Abbrev
		,v.[Description]
		,v.SwimmerID
		,v.IsRelay
		,v.EventDate
		,v.Split
		,v.IsCertified
		,v.IsProtested
		,v.Place
		,v.Points
		,v.HeatSheetID
		,v.Sequence
		,v.HeatSwimmerID
		,v.HeatSheetEventID
		,v.Leg
	from dbo.vwScore v
	inner join @HeatSheetEvent hse on hse.HeatSheetEventID = v.HeatSheetEventID
	order by HeatSheetID
			,Sequence
			,ElapsedTime
	
go

