
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatDeleteByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_HeatDeleteByHeatSheetEventID
	end
go

create procedure dbo.usp_HeatDeleteByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatDeleteByHeatSheetEventID
 
 Description:		Selects a Heat record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/31/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	delete dbo.Heat
	where HeatSheetEventID = @HeatSheetEventID
		
go

