
if exists (select * from sysobjects where type = 'P' and name = 'usp_UserSwimMeetGetAllBySystemUserID')
	begin
	    drop procedure dbo.usp_UserSwimMeetGetAllBySystemUserID
	end
go

create procedure dbo.usp_UserSwimMeetGetAllBySystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserSwimMeetGetAllBySystemUserID
 
 Description:		Selects a UserSwimMeet record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 4/4/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SystemUserID int

as
	select
		 SwimMeetID
		,SystemUserID
		,UserSwimMeetID
	from dbo.UserSwimMeet
	where SystemUserID = @SystemUserID
		
go

