
if exists (select * from sysobjects where type = 'P' and name = 'usp_LeagueGetAllCurrentSeasonBySystemUserID')
	begin
	    drop procedure dbo.usp_LeagueGetAllCurrentSeasonBySystemUserID
	end
go

create procedure dbo.usp_LeagueGetAllCurrentSeasonBySystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LeagueGetAllCurrentSeasonBySystemUserID
 
 Description:		Selects a League record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/5/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SystemUserID int

as
	select
		 l.[Description]
		,l.LeagueID
		,l.LeagueName
		,l.RegionID
		,r.RegionAbbrev
	from dbo.League l
	inner join dbo.Season s on s.LeagueID = l.LeagueID
	inner join dbo.TeamSeason ts on ts.SeasonID = s.SeasonID
	inner join dbo.UserTeam ut on ut.TeamID = ts.TeamID
	inner join dbo.Region r on r.RegionID = l.RegionID
	where ut.SystemUserID = @SystemUserID
	and s.EndDate > GETDATE()
		
go

