
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGet')
	begin
	    drop procedure dbo.usp_SeasonGet
	end
go

create procedure dbo.usp_SeasonGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGet
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
 ********************************************************************************************************/
 @SeasonID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,l.[Description] as LeagueDescription
		,L.LeagueName
	from dbo.Season s
	inner join dbo.League l on l.LeagueID = s.LeagueID
	where s.SeasonID = @SeasonID
		
go

