
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetBySeasonIDSystemUserID')
	begin
	    drop procedure dbo.usp_SeasonGetBySeasonIDSystemUserID
	end
go

create procedure dbo.usp_SeasonGetBySeasonIDSystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetBySeasonIDSystemUserID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/11/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
   AgeClassRuleID < System.Int32 >
   AgeClassRuleCustomDate < System.DateTime >
 ********************************************************************************************************/
 @SeasonID int
,@SystemUserID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,acr.Description as AgeClassRuleDescription
		,sign(coalesce(ul.UserLeagueID,0)) as IsAdmin
		,l.LeagueName
	from dbo.Season s
	inner join dbo.AgeClassRule acr on acr.AgeClassRuleID = s.AgeClassRuleID
	inner join dbo.League l on l.LeagueID = s.LeagueID
	left outer join dbo.UserLeague ul on ul.LeagueID = s.LeagueID
									 and ul.SystemUserID = @SystemUserID
	where s.SeasonID = @SeasonID		
go

