
if exists (select * from sysobjects where type = 'P' and name = 'usp_StrokeGet')
	begin
	    drop procedure dbo.usp_StrokeGet
	end
go

create procedure dbo.usp_StrokeGet
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_StrokeGet
 
 Description:		Selects a Stroke record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 7/12/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Stroke Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   StrokeID < System.Int32 >
 ********************************************************************************************************/
 @StrokeID int

as
	select
		 Description
		,IsRelay
		,StrokeID
	from dbo.Stroke
	where
		StrokeID = @StrokeID
		
go

