
if exists (select * from sysobjects where type = 'P' and name = 'usp_LeagueDelete')
	begin
	    drop procedure dbo.usp_LeagueDelete
	end
go

create procedure dbo.usp_LeagueDelete
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 -------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LeagueDelete
 
 Description:		Deletes a League record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 7/15/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @LeagueID int

as
	delete
	from dbo.League
	where
		LeagueID = @LeagueID

go

