
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetAllBySwimMeetID')
	begin
	    drop procedure dbo.usp_PoolConfigGetAllBySwimMeetID
	end
go

create procedure dbo.usp_PoolConfigGetAllBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetAllBySwimMeetID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/22/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the PoolConfig Entity
 The Entity expects the following properties to be returned:
   LaneCount < System.Int32 >
   LapLength < System.Int32 >
   PoolConfigID < System.Int32 >
   UOMID < System.Int32 >
 ********************************************************************************************************/
 @SwimMeetID int

as
select	 pc.CreatedByUserID
		,pc.CreatedDate
		,pc.[Description]
		,pc.LaneCount
		,pc.LaneLength
		,pc.ModifiedByUserID
		,pc.ModifiedDate
		,pc.PoolConfigID
		,pc.PoolID
		,pc.UOMID
		,l.Name as LocationName
		,u.Abbrev as UOMAbbrev
		,p.[Description] as PoolDescription
	from dbo.PoolConfig pc
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.Location l on l.LocationID = p.LocationID
	inner join dbo.SwimMeet sm on sm.LocationID = p.LocationID
	inner join dbo.UOM u on u.UOMID = pc.UOMID
	where sm.SwimMeetID = @SwimMeetID
	group by pc.CreatedByUserID
			,pc.CreatedDate
			,pc.[Description]
			,pc.LaneCount
			,pc.LaneLength
			,pc.ModifiedByUserID
			,pc.ModifiedDate
			,pc.PoolConfigID
			,pc.PoolID
			,pc.UOMID
			,l.Name
			,u.Abbrev
			,p.[Description]
		
go

