
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetAllByLeagueIDSystemUserID')
	begin
	    drop procedure dbo.usp_SeasonGetAllByLeagueIDSystemUserID
	end
go

create procedure dbo.usp_SeasonGetAllByLeagueIDSystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetAllByLeagueIDSystemUserID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/14/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @LeagueID int
,@SystemUserID int

as
;
with AdminLeagues (LeagueID) as(
		select ul.LeagueID
		from dbo.UserLeague ul 
		where ul.SystemUserID = @SystemUserID
		and ul.LeagueID = @LeagueID
		group by ul.LeagueID
),

	MemberLeagues (LeagueID) as (
	select l.LeagueID
	from dbo.League l
	inner join dbo.TeamSeason ts on ts.LeagueID = l.LeagueID
	inner join dbo.SwimmerTeamSeason sts on sts.TeamSeasonID = ts.TeamSeasonID
	inner join dbo.UserSwimmer us on us.SwimmerID = sts.SwimmerID
	where us.SystemUserID = @SystemUserID
	and l.LeagueID = @LeagueID
	and l.LeagueID not in (	select ul.LeagueID
							from dbo.UserLeague ul 
							where ul.SystemUserID = @SystemUserID)
)

	--League/Seasons that SystemUser administrates
	select
		 s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,s.AgeClassRuleID
		,s.AgeClassRuleCustomDate
		,cast(1 as bit) as IsAdmin
	from dbo.Season s
	inner join AdminLeagues l on l.LeagueID = s.LeagueID
		
	union 

	--League/Seasons that SystemUser has a swimmer involved in
	select
		 s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,s.AgeClassRuleID
		,s.AgeClassRuleCustomDate
		,cast(0 as bit) as IsAdmin
	from dbo.Season s
	inner join MemberLeagues l on l.LeagueID = s.LeagueID
	
	go

