
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolGetAllBySwimMeetID')
	begin
	    drop procedure dbo.usp_PoolGetAllBySwimMeetID
	end
go

create procedure dbo.usp_PoolGetAllBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolGetAllBySwimMeetID
 
 Description:		Selects a Pool record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/9/2009  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Pool Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   LocationID < System.Int32 >
   PoolID < System.Int32 >
 ********************************************************************************************************/
 @SwimMeetID int

as
	select	 p.CreatedByUserID
			,p.CreatedDate
			,p.[Description]
			,p.LocationID
			,p.ModifiedByUserID
			,p.ModifiedDate
			,p.PoolID
	from dbo.[Pool] p
	inner join dbo.SwimMeet sm on sm.LocationID = p.LocationID
	where sm.SwimMeetID = @SwimMeetID
				
go

