
if exists (select * from sysobjects where type = 'P' and name = 'usp_StrokeGetByHeatSheetEventID')
	begin
	    drop procedure dbo.usp_StrokeGetByHeatSheetEventID
	end
go

create procedure dbo.usp_StrokeGetByHeatSheetEventID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_StrokeGetByHeatSheetEventID
 
 Description:		Selects a Stroke record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/16/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Stroke Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   StrokeID < System.Int32 >
   IsRelay < System.Boolean >
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	select	 s.[Description]
			,s.StrokeID
			,s.IsRelay
	from dbo.Stroke s
	inner join dbo.SwimEvent se on se.StrokeID = s.StrokeID
	inner join dbo.HeatSheetEvent hse on hse.SwimEventID = se.SwimEventID
	where hse.HeatSheetEventID = @HeatSheetEventID
		
go

