
if exists (select * from sysobjects where type = 'P' and name = 'usp_LaneSequenceGetAllByLaneCount')
	begin
	    drop procedure dbo.usp_LaneSequenceGetAllByLaneCount
	end
go

create procedure dbo.usp_LaneSequenceGetAllByLaneCount
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_LaneSequenceGetAllByLaneCount
 
 Description:		Selects a LaneSequence record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 1/6/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the LaneSequence Entity
 The Entity expects the following properties to be returned:
   LaneCount < System.Int32 >
   LaneNumber < System.Int32 >
   LaneOrder < System.Int32 >
 ********************************************************************************************************/
 @LaneCount int

as
	select
		 LaneCount
		,LaneNumber
		,LaneOrder
	from dbo.LaneSequence
	where
		LaneCount = @LaneCount
		
go

