
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamLeagueRequestGetAllBySeasonIDSystemUserID')
	begin
	    drop procedure dbo.usp_TeamLeagueRequestGetAllBySeasonIDSystemUserID
	end
go

create procedure dbo.usp_TeamLeagueRequestGetAllBySeasonIDSystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamLeagueRequestGetAllBySeasonIDSystemUserID
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/14/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
   HomePoolConfigID < System.Int32 >
 ********************************************************************************************************/
 @SeasonID int
,@SystemUserID int

as
	select
		 t.TeamID
		,t.TeamName
		,t.Abbrev
		,t.HomePoolConfigID
		,ut.UserTeamID
		,l.Name as LocationName
		,tlr.TeamLeagueRequestID
	from dbo.Team t
	inner join dbo.PoolConfig pc on pc.PoolConfigID = t.HomePoolConfigID
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.Location l on l.LocationID = p.LocationID
	inner join dbo.UserTeam ut on ut.TeamID = t.TeamID
	inner join dbo.TeamLeagueRequest tlr on tlr.UserTeamID = ut.UserTeamID
	inner join dbo.Season s on s.SeasonID = tlr.SeasonID
	inner join dbo.UserLeague ul on ul.LeagueID = s.LeagueID
	where tlr.SeasonID = @SeasonID
	and tlr.IsApproved = 0
	and	ul.SystemUserID = @SystemUserID
		
go

