
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamGetAllCurrentSeasonByLeagueID')
	begin
	    drop procedure dbo.usp_TeamGetAllCurrentSeasonByLeagueID
	end
go

create procedure dbo.usp_TeamGetAllCurrentSeasonByLeagueID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamGetAllCurrentSeasonByLeagueID
 
 Description:		Selects a Team record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/5/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Team Entity
 The Entity expects the following properties to be returned:
   TeamID < System.Int32 >
   TeamName < System.String >
   Abbrev < System.String >
 ********************************************************************************************************/
 @LeagueID int

as
	select
		 t.TeamID
		,t.TeamName
		,t.Abbrev
	from dbo.Team t
	inner join dbo.TeamSeason ts on ts.TeamID = t.TeamID
	inner join dbo.Season s on s.SeasonID = ts.SeasonID
	where s.LeagueID = @LeagueID
	and s.EndDate > GETDATE()
		
go

