if exists (select * from sysobjects where type = 'P' and name = 'usp_UserSwimMeetSave')
	begin
	    drop procedure dbo.usp_UserSwimMeetSave
	end
go

create procedure dbo.usp_UserSwimMeetSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_UserSwimMeetSave

 Description:		Saves an UserSwimMeet record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/19/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int
,@SystemUserID int
,@UserSwimMeetID int

as
	declare @InsertedPrimaryKeyTable table (UserSwimMeetID int)
		
	if exists (select 1 from dbo.UserSwimMeet where UserSwimMeetID = @UserSwimMeetID)
		begin
			
			update dbo.UserSwimMeet
			set
				 SwimMeetID = @SwimMeetID
				,SystemUserID = @SystemUserID
			output inserted.UserSwimMeetID into @InsertedPrimaryKeyTable
			where UserSwimMeetID = @UserSwimMeetID
		end
	--prevent duplicates
	if exists(select 1 from dbo.UserSwimMeet where SystemUserID = @SystemUserID and SwimMeetID = @SwimMeetID)
		begin
			insert into @InsertedPrimaryKeyTable
			select UserSwimMeetID from dbo.UserSwimMeet where SystemUserID = @SystemUserID and SwimMeetID = @SwimMeetID
		end
	else
		begin
			insert into dbo.UserSwimMeet(
				 SwimMeetID
				,SystemUserID
			)
			output inserted.UserSwimMeetID into @InsertedPrimaryKeyTable
			values (
				 @SwimMeetID
				,@SystemUserID
			)
			
		end

	select UserSwimMeetID from @InsertedPrimaryKeyTable
		
go

