
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetTeamGetAllBySwimMeetID')
	begin
	    drop procedure dbo.usp_SwimMeetTeamGetAllBySwimMeetID
	end
go

create procedure dbo.usp_SwimMeetTeamGetAllBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetTeamGetAllBySwimMeetID
 
 Description:		Selects a SwimMeetTeam record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 7/8/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int

as
	select
		 smt.SwimMeetID
		,smt.SwimMeetTeamID
		,smt.TeamSeasonID
		,smt.IsHomeTeam
		,t.TeamName
		,t.Abbrev
	from dbo.SwimMeetTeam smt
	inner join dbo.TeamSeason ts on ts.TeamID = smt.TeamSeasonID 
	inner join dbo.Team t on t.TeamID = ts.TeamID
	where smt.SwimMeetID = @SwimMeetID
		
go

