
if exists (select * from sysobjects where type = 'P' and name = 'usp_ResultGetAllByHeatSheetEventIDSwimmerID')
	begin
	    drop procedure dbo.usp_ResultGetAllByHeatSheetEventIDSwimmerID
	end
go

create procedure dbo.usp_ResultGetAllByHeatSheetEventIDSwimmerID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ResultGetAllByHeatSheetEventIDSwimmerID
 
 Description:		Selects a Result record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 9/22/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetEventID int
,@SwimmerID int

as

	--Get the Stroke and Distance for the Event
	declare	 @StrokeID int
			,@Distance int
	select	 @StrokeID = se.StrokeID
			,@Distance = hse.Distance
	from dbo.SwimEvent se
	inner join dbo.HeatSheetEvent hse on hse.SwimEventID = se.SwimEventID
	where hse.HeatSheetEventID = @HeatSheetEventID

	--Get all results for the swimmer in the given stroke & Distance
	select
		 r.AgeClassID
		,r.CreatedByUserID
		,r.CreatedDate
		,r.Disqualified
		,r.Distance
		,r.ElapsedTime
		,r.EventDate
		,r.HeatSwimmerID
		,r.IsCertified
		,r.IsProtested
		,r.LaneLength
		,r.ModifiedByUserID
		,r.ModifiedDate
		,r.Place
		,r.Points
		,r.ResultID
		,r.ScoringSchemeID
		,r.Split
		,r.StrokeID
		,r.SwimmerID
		,r.SwimmerTeamSeasonID
		,r.TeamSeasonID
		,r.UOMID
	from dbo.Result r
	where r.SwimmerID = @SwimmerID
	and r.StrokeID = @StrokeID
	and r.Distance = @Distance		
go

