
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetAllByTeamID')
	begin
	    drop procedure dbo.usp_SeasonGetAllByTeamID
	end
go

create procedure dbo.usp_SeasonGetAllByTeamID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetAllByTeamID
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/18/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
 ********************************************************************************************************/
 @TeamID int

as
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,l.LeagueName
		,l.Description as LeagueDescription
		,ts.TeamSeasonID
	from dbo.Season s
	inner join dbo.TeamSeason ts on ts.SeasonID = s.SeasonID
	inner join dbo.League l on l.LeagueID = s.LeagueID
	where ts.TeamID = @TeamID
		
go

