
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetEventDelete')
	begin
	    drop procedure dbo.usp_HeatSheetEventDelete
	end
go

create procedure dbo.usp_HeatSheetEventDelete
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 -------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetEventDelete
 
 Description:		Deletes a HeatSheetEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/13/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetEventID int

as
	delete
	from dbo.HeatSheetEvent
	where
		HeatSheetEventID = @HeatSheetEventID

go

