
if exists (select * from sysobjects where type = 'P' and name = 'usp_TeamSeasonGetAllBySystemUserID')
	begin
	    drop procedure dbo.usp_TeamSeasonGetAllBySystemUserID
	end
go

create procedure dbo.usp_TeamSeasonGetAllBySystemUserID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_TeamSeasonGetAllBySystemUserID
 
 Description:		Returns all current and future TeamSeason records for the given systemuser
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 5/15/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SystemUserID int

as
	select
		 ts.SeasonID
		,ts.TeamID
		,ts.TeamSeasonID
		,ts.LeagueID
		,ts.AgeClassRuleID
	from dbo.TeamSeason ts
	inner join dbo.UserTeam ut on ut.TeamID = ts.TeamID
	inner join dbo.Season s on s.SeasonID = ts.SeasonID 
	where ut.SystemUserID = @SystemUserID
	and s.StartDate >= GETDATE()		
go

