
if exists (select * from sysobjects where type = 'P' and name = 'usp_PoolConfigGetByUserTeamID')
	begin
	    drop procedure dbo.usp_PoolConfigGetByUserTeamID
	end
go

create procedure dbo.usp_PoolConfigGetByUserTeamID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_PoolConfigGetByUserTeamID
 
 Description:		Selects a PoolConfig record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/28/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @UserTeamID int

as
	select	 pc.CreatedByUserID
			,pc.CreatedDate
			,pc.[Description]
			,pc.LaneCount
			,pc.LaneLength
			,pc.ModifiedByUserID
			,pc.ModifiedDate
			,pc.PoolConfigID
			,pc.PoolID
			,pc.UOMID
			,l.Name as LocationName
			,l.City
			,r.RegionAbbrev
			,l.RegionID
			,u.Abbrev as UOMAbbrev
			,p.[Description] as PoolDescription
	from dbo.PoolConfig pc
	inner join dbo.Team t on t.HomePoolConfigID = pc.PoolConfigID
	inner join dbo.UserTeam ut on ut.TeamID = t.TeamID
	inner join dbo.[Pool] p on p.PoolID = pc.PoolID
	inner join dbo.UOM u on u.UOMID = pc.UOMID
	inner join dbo.Location l on l.LocationID = p.LocationID
	inner join dbo.Region r on r.RegionID = l.RegionID
	where ut.UserTeamID = @UserTeamID
		
go

