
if exists (select * from sysobjects where type = 'P' and name = 'usp_ScoreGetAllBySwimMeetID')
	begin
	    drop procedure dbo.usp_ScoreGetAllBySwimMeetID
	end
go

create procedure dbo.usp_ScoreGetAllBySwimMeetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_ScoreGetAllBySwimMeetID
 
 Description:		Selects a Score record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 2/12/2011  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int

as
	select
		 SwimMeetID
		,HeatSheetID
		,HeatSheetEventID
		,HeatSwimmerID
		,Sequence				
		,Disqualified
		,TeamID
		,ElapsedTime
		,Leg
		,Swimmer
		,LaneLength
		,Abbrev
		,[Description]
		,SwimmerID
		,IsRelay
		,EventDate
		,Split
		,IsCertified
		,IsProtested
		,Place
		,Points
	from dbo.vwScore
	where SwimMeetID = @SwimMeetID
	order by HeatSheetID
			,Sequence
			,ElapsedTime
	
go

