
if exists (select * from sysobjects where type = 'P' and name = 'usp_StrokeGetByHeatID')
	begin
	    drop procedure dbo.usp_StrokeGetByHeatID
	end
go

create procedure dbo.usp_StrokeGetByHeatID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_StrokeGetByHeatID
 
 Description:		Selects a Stroke record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 8/10/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatID int

as
	select
		 s.[Description]
		,s.StrokeID
		,s.IsRelay
	from dbo.Stroke s
	inner join dbo.SwimEvent se on se.StrokeID = s.StrokeID
	inner join dbo.HeatSheetEvent hse on hse.SwimEventID = se.SwimEventID
	inner join dbo.Heat h on h.HeatSheetEventID = hse.HeatSheetEventID
	where h.HeatID = @HeatID
		
go

