
if exists (select * from sysobjects where type = 'P' and name = 'usp_SeasonGetAllBySearch')
	begin
	    drop procedure dbo.usp_SeasonGetAllBySearch
	end
go

create procedure dbo.usp_SeasonGetAllBySearch
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SeasonGetAllBySearch
 
 Description:		Selects a Season record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 12/20/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the Season Entity
 The Entity expects the following properties to be returned:
   Description < System.String >
   EndDate < System.DateTime >
   SeasonID < System.Int32 >
   StartDate < System.DateTime >
   LeagueID < System.Int32 >
 ********************************************************************************************************/
 @LeagueName varchar(100)
,@RegionID int

as

	if @RegionID = 0 set @RegionID = null
	if @LeagueName = '' set @LeagueName = null
	
	select
		 s.AgeClassRuleCustomDate
		,s.AgeClassRuleID
		,s.[Description]
		,s.EndDate
		,s.SeasonID
		,s.StartDate
		,s.LeagueID
		,lg.LeagueName
		,lg.[Description] as LeagueDescription
	from dbo.Season s
	inner join dbo.League lg on lg.LeagueID = s.LeagueID
	where s.EndDate > GETDATE()	
	and	(lg.LeagueName like '%' + @LeagueName +'%' or @LeagueName is null)
	and	(lg.RegionID = @RegionID or @RegionID is null)
		
go

