
if exists (select * from sysobjects where type = 'P' and name = 'usp_SwimMeetDelete')
	begin
	    drop procedure dbo.usp_SwimMeetDelete
	end
go

create procedure dbo.usp_SwimMeetDelete
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 -------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_SwimMeetDelete
 
 Description:		Deletes a SwimMeet and all child records
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/1/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @SwimMeetID int

as
	begin try
		begin tran

			delete hs
			from dbo.HeatSwimmer hs
			inner join dbo.Heat h on h.HeatID = hs.HeatID
			inner join dbo.HeatSheetEvent hse on hse.HeatSheetEventID = h.HeatSheetEventID
			inner join dbo.HeatSheet hst on hst.HeatSheetID = hse.HeatSheetID
			where hst.SwimMeetID = @SwimMeetID

			delete h
			from dbo.Heat h 
			inner join dbo.HeatSheetEvent hse on hse.HeatSheetEventID = h.HeatSheetEventID
			inner join dbo.HeatSheet hst on hst.HeatSheetID = hse.HeatSheetID
			where hst.SwimMeetID = @SwimMeetID

			delete hse
			from dbo.HeatSheetEvent hse 
			inner join dbo.HeatSheet hst on hst.HeatSheetID = hse.HeatSheetID
			where hst.SwimMeetID = @SwimMeetID

			delete hst
			from dbo.HeatSheetTeam hst
			inner join dbo.HeatSheet hs on hs.HeatSheetID = hst.HeatSheetID
			where hs.SwimMeetID = @SwimMeetID
			
			delete hst
			from dbo.HeatSheet hst
			where hst.SwimMeetID = @SwimMeetID

			delete
			from dbo.UserSwimMeet
			where SwimMeetID = @SwimMeetID
			
			delete
			from dbo.SwimMeetTeam
			where SwimMeetID = @SwimMeetID

			delete
			from dbo.SwimMeet
			where SwimMeetID = @SwimMeetID

		commit tran
	end try
	
	begin catch
		rollback tran
	end catch
go

