
if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetEventGetByDistanceSwimEventIDHeatSheetID')
	begin
	    drop procedure dbo.usp_HeatSheetEventGetByDistanceSwimEventIDHeatSheetID
	end
go

create procedure dbo.usp_HeatSheetEventGetByDistanceSwimEventIDHeatSheetID
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetEventGetByDistanceSwimEventIDHeatSheetID
 
 Description:		Selects a HeatSheetEvent record for the given parameters
 
 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 10/12/2010  Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************
 The result of this procedure call is used to populate the HeatSheetEvent Entity
 The Entity expects the following properties to be returned:
   Sequence < System.Int32 >
   SwimEventID < System.Int32 >
   HeatSheetEventID < System.Int32 >
   Distance < System.Int32 >
   HeatSheetID < System.Int32 >
 ********************************************************************************************************/
 @Distance int
,@HeatSheetID int
,@SwimEventID int

as
	select
		 Sequence
		,SwimEventID
		,HeatSheetEventID
		,Distance
		,HeatSheetID
	from dbo.HeatSheetEvent
	where
		Distance = @Distance
	and	HeatSheetID = @HeatSheetID
	and	SwimEventID = @SwimEventID
		
go

