if exists (select * from sysobjects where type = 'P' and name = 'usp_HeatSheetSave')
	begin
	    drop procedure dbo.usp_HeatSheetSave
	end
go

create procedure dbo.usp_HeatSheetSave
 /*******************************************************************************************************
 Logical Advantage, LLC
 www.logicaladvantage.com
 704-377-5066
 --------------------------------------------------------------------------------------------------------
 Stored Procedure:	usp_HeatSheetSave

 Description:		Saves an HeatSheet record for the given parameters

 --------------------------------------------------------------------------------------------------------
 Change Log:
 v1.0.0 - 11/22/2010	Original Release - Generated by LAAF
 ********************************************************************************************************
 To keep the Generator from overwriting this file add the word NOT between the center asterisks ( *NOT* )
 *** DO *NOT* GENERATE ***
 ********************************************************************************************************/
 @HeatSheetID int
,@PoolConfigID int
,@SwimMeetID int

as
	declare @InsertedPrimaryKeyTable table (HeatSheetID int)
		
	if exists (select 1 from dbo.HeatSheet where HeatSheetID = @HeatSheetID)
		begin
			
			update dbo.HeatSheet
			set
				 PoolConfigID = @PoolConfigID
				,SwimMeetID = @SwimMeetID
			output inserted.HeatSheetID into @InsertedPrimaryKeyTable
			where HeatSheetID = @HeatSheetID
		end
	--prevent duplicates
	if exists(select 1 from dbo.HeatSheet where SwimMeetID = @SwimMeetID and PoolConfigID = @PoolConfigID)
		begin
			insert into @InsertedPrimaryKeyTable
			select HeatSheetID from dbo.HeatSheet where SwimMeetID = @SwimMeetID and PoolConfigID = @PoolConfigID
		end
	else
		begin
			insert into dbo.HeatSheet(
				 PoolConfigID
				,SwimMeetID
			)
			output inserted.HeatSheetID into @InsertedPrimaryKeyTable
			values (
				 @PoolConfigID
				,@SwimMeetID
			)
			
		end

	select HeatSheetID from @InsertedPrimaryKeyTable
		
go

