namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _AgeClassManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    public class _AgeClassManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _AgeClassManager()
        {
        }
        
        public _AgeClassManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int AgeClassSave(Swimomatic.Entity.AgeClass AgeClass)
        {
            return ((int)(ServiceProvider.AgeClassSave(AgeClass.AgeClassID, AgeClass.Description, AgeClass.IsMale, AgeClass.MaxAge, AgeClass.MinAge)));
        }
        
        public virtual void AgeClassDelete(int AgeClassID)
        {
            ServiceProvider.AgeClassDelete(AgeClassID);
        }
        
        public virtual Swimomatic.Entity.AgeClass AgeClassGet(int AgeClassID)
        {
            return ((Swimomatic.Entity.AgeClass)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.AgeClass(), ServiceProvider.AgeClassGet(AgeClassID))));
        }
        
        public virtual Swimomatic.Entity.AgeClassCollection AgeClassGetAll()
        {
            return ((Swimomatic.Entity.AgeClassCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.AgeClass), typeof(Swimomatic.Entity.AgeClassCollection), ServiceProvider.AgeClassGetAll())));
        }
        
        public virtual Swimomatic.Entity.AgeClass AgeClassGetByAgeClassRuleIDBirthDate(int AgeClassRuleID, System.DateTime BirthDate)
        {
            return ((Swimomatic.Entity.AgeClass)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.AgeClass(), ServiceProvider.AgeClassGetByAgeClassRuleIDBirthDate(AgeClassRuleID, BirthDate))));
        }
    }
}
