namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _HeatSheetTeamManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/13/2011] - Generated by LAAF CodeGen
    // </history>
    public class _HeatSheetTeamManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _HeatSheetTeamManager()
        {
        }
        
        public _HeatSheetTeamManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int HeatSheetTeamSave(Swimomatic.Entity.HeatSheetTeam HeatSheetTeam)
        {
            return ((int)(ServiceProvider.HeatSheetTeamSave(HeatSheetTeam.HeatSheetID, HeatSheetTeam.HeatSheetTeamID, HeatSheetTeam.Lanes, HeatSheetTeam.TeamSeasonID)));
        }
        
        public virtual void HeatSheetTeamDelete(int HeatSheetTeamID)
        {
            ServiceProvider.HeatSheetTeamDelete(HeatSheetTeamID);
        }
        
        public virtual Swimomatic.Entity.HeatSheetTeam HeatSheetTeamGet(int HeatSheetTeamID)
        {
            return ((Swimomatic.Entity.HeatSheetTeam)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.HeatSheetTeam(), ServiceProvider.HeatSheetTeamGet(HeatSheetTeamID))));
        }
        
        public virtual Swimomatic.Entity.HeatSheetTeamCollection HeatSheetTeamGetAllByHeatSheetEventID(int HeatSheetEventID)
        {
            return ((Swimomatic.Entity.HeatSheetTeamCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.HeatSheetTeam), typeof(Swimomatic.Entity.HeatSheetTeamCollection), ServiceProvider.HeatSheetTeamGetAllByHeatSheetEventID(HeatSheetEventID))));
        }
    }
}
