namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _LaneSequenceManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 01/06/2011] - Generated by LAAF CodeGen
    // </history>
    public class _LaneSequenceManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _LaneSequenceManager()
        {
        }
        
        public _LaneSequenceManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual Swimomatic.Entity.LaneSequenceCollection LaneSequenceGetAllByLaneCount(int LaneCount)
        {
            return ((Swimomatic.Entity.LaneSequenceCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.LaneSequence), typeof(Swimomatic.Entity.LaneSequenceCollection), ServiceProvider.LaneSequenceGetAllByLaneCount(LaneCount))));
        }
    }
}
