namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _RegionManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    public class _RegionManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _RegionManager()
        {
        }
        
        public _RegionManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int RegionSave(Swimomatic.Entity.Region Region)
        {
            return ((int)(ServiceProvider.RegionSave(Region.RegionAbbrev, Region.RegionID, Region.RegionName)));
        }
        
        public virtual void RegionDelete(int RegionID)
        {
            ServiceProvider.RegionDelete(RegionID);
        }
        
        public virtual Swimomatic.Entity.Region RegionGet(int RegionID)
        {
            return ((Swimomatic.Entity.Region)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.Region(), ServiceProvider.RegionGet(RegionID))));
        }
        
        public virtual Swimomatic.Entity.RegionCollection RegionGetAll()
        {
            return ((Swimomatic.Entity.RegionCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.Region), typeof(Swimomatic.Entity.RegionCollection), ServiceProvider.RegionGetAll())));
        }
    }
}
