namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _StrokeManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    public class _StrokeManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _StrokeManager()
        {
        }
        
        public _StrokeManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int StrokeSave(Swimomatic.Entity.Stroke Stroke)
        {
            return ((int)(ServiceProvider.StrokeSave(Stroke.Description, Stroke.IsRelay, Stroke.StrokeID)));
        }
        
        public virtual void StrokeDelete(int StrokeID)
        {
            ServiceProvider.StrokeDelete(StrokeID);
        }
        
        public virtual Swimomatic.Entity.Stroke StrokeGet(int StrokeID)
        {
            return ((Swimomatic.Entity.Stroke)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.Stroke(), ServiceProvider.StrokeGet(StrokeID))));
        }
        
        public virtual Swimomatic.Entity.StrokeCollection StrokeGetAll()
        {
            return ((Swimomatic.Entity.StrokeCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.Stroke), typeof(Swimomatic.Entity.StrokeCollection), ServiceProvider.StrokeGetAll())));
        }
        
        public virtual Swimomatic.Entity.Stroke StrokeGetByHeatID(int HeatID)
        {
            return ((Swimomatic.Entity.Stroke)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.Stroke(), ServiceProvider.StrokeGetByHeatID(HeatID))));
        }
        
        public virtual Swimomatic.Entity.Stroke StrokeGetByHeatSheetEventID(int HeatSheetEventID)
        {
            return ((Swimomatic.Entity.Stroke)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.Stroke(), ServiceProvider.StrokeGetByHeatSheetEventID(HeatSheetEventID))));
        }
    }
}
