namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimEventManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    public class _SwimEventManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _SwimEventManager()
        {
        }
        
        public _SwimEventManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int SwimEventSave(Swimomatic.Entity.SwimEvent SwimEvent)
        {
            return ((int)(ServiceProvider.SwimEventSave(SwimEvent.AgeClassID, SwimEvent.Description, SwimEvent.StrokeID, SwimEvent.SwimEventID)));
        }
        
        public virtual void SwimEventDelete(int SwimEventID)
        {
            ServiceProvider.SwimEventDelete(SwimEventID);
        }
        
        public virtual Swimomatic.Entity.SwimEvent SwimEventGet(int SwimEventID)
        {
            return ((Swimomatic.Entity.SwimEvent)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.SwimEvent(), ServiceProvider.SwimEventGet(SwimEventID))));
        }
        
        public virtual Swimomatic.Entity.SwimEventCollection SwimEventGetAll()
        {
            return ((Swimomatic.Entity.SwimEventCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.SwimEvent), typeof(Swimomatic.Entity.SwimEventCollection), ServiceProvider.SwimEventGetAll())));
        }
        
        public virtual Swimomatic.Entity.SwimEvent SwimEventGetByAgeClassIDStrokeID(int AgeClassID, int StrokeID)
        {
            return ((Swimomatic.Entity.SwimEvent)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.SwimEvent(), ServiceProvider.SwimEventGetByAgeClassIDStrokeID(AgeClassID, StrokeID))));
        }
    }
}
