namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _TeamLeagueRequestManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/08/2010] - Generated by LAAF CodeGen
    // </history>
    public class _TeamLeagueRequestManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _TeamLeagueRequestManager()
        {
        }
        
        public _TeamLeagueRequestManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int TeamLeagueRequestSave(Swimomatic.Entity.TeamLeagueRequest TeamLeagueRequest)
        {
            return ((int)(ServiceProvider.TeamLeagueRequestSave(TeamLeagueRequest.ApprovalDate, TeamLeagueRequest.ApprovalUserID, TeamLeagueRequest.IsApproved, TeamLeagueRequest.RequestDate, TeamLeagueRequest.SeasonID, TeamLeagueRequest.TeamLeagueRequestID, TeamLeagueRequest.UserTeamID)));
        }
        
        public virtual void TeamLeagueRequestDelete(int TeamLeagueRequestID)
        {
            ServiceProvider.TeamLeagueRequestDelete(TeamLeagueRequestID);
        }
        
        public virtual Swimomatic.Entity.TeamLeagueRequest TeamLeagueRequestGet(int TeamLeagueRequestID)
        {
            return ((Swimomatic.Entity.TeamLeagueRequest)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.TeamLeagueRequest(), ServiceProvider.TeamLeagueRequestGet(TeamLeagueRequestID))));
        }
        
        public virtual Swimomatic.Entity.TeamLeagueRequestCollection TeamLeagueRequestGetAll()
        {
            return ((Swimomatic.Entity.TeamLeagueRequestCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.TeamLeagueRequest), typeof(Swimomatic.Entity.TeamLeagueRequestCollection), ServiceProvider.TeamLeagueRequestGetAll())));
        }
    }
}
