namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserSwimMeetManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 04/04/2011] - Generated by LAAF CodeGen
    // </history>
    public class _UserSwimMeetManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _UserSwimMeetManager()
        {
        }
        
        public _UserSwimMeetManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int UserSwimMeetSave(Swimomatic.Entity.UserSwimMeet UserSwimMeet)
        {
            return ((int)(ServiceProvider.UserSwimMeetSave(UserSwimMeet.SwimMeetID, UserSwimMeet.SystemUserID, UserSwimMeet.UserSwimMeetID)));
        }
        
        public virtual void UserSwimMeetDelete(int UserSwimMeetID)
        {
            ServiceProvider.UserSwimMeetDelete(UserSwimMeetID);
        }
        
        public virtual Swimomatic.Entity.UserSwimMeet UserSwimMeetGet(int UserSwimMeetID)
        {
            return ((Swimomatic.Entity.UserSwimMeet)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.UserSwimMeet(), ServiceProvider.UserSwimMeetGet(UserSwimMeetID))));
        }
        
        public virtual Swimomatic.Entity.UserSwimMeetCollection UserSwimMeetGetAll()
        {
            return ((Swimomatic.Entity.UserSwimMeetCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.UserSwimMeet), typeof(Swimomatic.Entity.UserSwimMeetCollection), ServiceProvider.UserSwimMeetGetAll())));
        }
        
        public virtual Swimomatic.Entity.UserSwimMeetCollection UserSwimMeetGetAllBySystemUserID(int SystemUserID)
        {
            return ((Swimomatic.Entity.UserSwimMeetCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.UserSwimMeet), typeof(Swimomatic.Entity.UserSwimMeetCollection), ServiceProvider.UserSwimMeetGetAllBySystemUserID(SystemUserID))));
        }
    }
}
