namespace Swimomatic.Manager
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserTeamManager class is the base manager class.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/19/2011] - Generated by LAAF CodeGen
    // </history>
    public class _UserTeamManager
    {
        
        private Swimomatic.ServiceProvider.SwimomaticServiceProvider _ServiceProvider;
        
        #region  Constructor 
        public _UserTeamManager()
        {
        }
        
        public _UserTeamManager(Swimomatic.ServiceProvider.SwimomaticServiceProvider serviceProvider)
        {
            _ServiceProvider = serviceProvider;
        }
        #endregion
        
        #region  Service Provider 
        public virtual Swimomatic.ServiceProvider.SwimomaticServiceProvider ServiceProvider
        {
            get
            {
                if ((_ServiceProvider == null))
                {
                    _ServiceProvider = Swimomatic.ServiceProvider.SwimomaticServiceProvider.GetInstance();
                }
                return _ServiceProvider;
            }
        }
        #endregion
        
        public virtual int UserTeamSave(Swimomatic.Entity.UserTeam UserTeam)
        {
            return ((int)(ServiceProvider.UserTeamSave(UserTeam.SystemUserID, UserTeam.TeamID, UserTeam.UserTeamID)));
        }
        
        public virtual void UserTeamDelete(int UserTeamID)
        {
            ServiceProvider.UserTeamDelete(UserTeamID);
        }
        
        public virtual Swimomatic.Entity.UserTeam UserTeamGet(int UserTeamID)
        {
            return ((Swimomatic.Entity.UserTeam)(LAAF.Data.Helper.MapDataToLAEntity(new Swimomatic.Entity.UserTeam(), ServiceProvider.UserTeamGet(UserTeamID))));
        }
        
        public virtual Swimomatic.Entity.UserTeamCollection UserTeamGetAllByTeamSeasonID(int TeamSeasonID)
        {
            return ((Swimomatic.Entity.UserTeamCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.UserTeam), typeof(Swimomatic.Entity.UserTeamCollection), ServiceProvider.UserTeamGetAllByTeamSeasonID(TeamSeasonID))));
        }
        
        public virtual Swimomatic.Entity.UserTeamCollection UserTeamGetAllBySystemUserID(int SystemUserID)
        {
            return ((Swimomatic.Entity.UserTeamCollection)(LAAF.Data.Helper.MapDataToLAEntityCollection(typeof(Swimomatic.Entity.UserTeam), typeof(Swimomatic.Entity.UserTeamCollection), ServiceProvider.UserTeamGetAllBySystemUserID(SystemUserID))));
        }
    }
}
