namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _AgeClassRule class is the base class representing a single AgeClassRule object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/05/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _AgeClassRule : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _AgeClassRuleID;
        
        private string _Description;
        
        private string _ShortDescription;
        #endregion
        
        #region  Constructor 
        public _AgeClassRule()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int AgeClassRuleID
        {
            get
            {
                return _AgeClassRuleID;
            }
            set
            {
                _AgeClassRuleID = value;
            }
        }
        
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual string ShortDescription
        {
            get
            {
                return _ShortDescription;
            }
            set
            {
                _ShortDescription = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            AgeClassRuleID,
            
            Description,
            
            ShortDescription,
        }
    }
}
