namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Heat class is the base class representing a single Heat object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Heat : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _HeatID;
        
        private int _HeatNumber;
        
        private int _HeatSheetEventID;
        #endregion
        
        #region  Constructor 
        public _Heat()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int HeatID
        {
            get
            {
                return _HeatID;
            }
            set
            {
                _HeatID = value;
            }
        }
        
        public virtual int HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                _HeatNumber = value;
            }
        }
        
        public virtual int HeatSheetEventID
        {
            get
            {
                return _HeatSheetEventID;
            }
            set
            {
                _HeatSheetEventID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            HeatID,
            
            HeatNumber,
            
            HeatSheetEventID,
        }
    }
}
