namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _HeatSheetEvent class is the base class representing a single HeatSheetEvent object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _HeatSheetEvent : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _Sequence;
        
        private int _SwimEventID;
        
        private int _HeatSheetEventID;
        
        private int _Distance;
        
        private int _HeatSheetID;
        #endregion
        
        #region  Constructor 
        public _HeatSheetEvent()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                _Sequence = value;
            }
        }
        
        public virtual int SwimEventID
        {
            get
            {
                return _SwimEventID;
            }
            set
            {
                _SwimEventID = value;
            }
        }
        
        public virtual int HeatSheetEventID
        {
            get
            {
                return _HeatSheetEventID;
            }
            set
            {
                _HeatSheetEventID = value;
            }
        }
        
        public virtual int Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                _Distance = value;
            }
        }
        
        public virtual int HeatSheetID
        {
            get
            {
                return _HeatSheetID;
            }
            set
            {
                _HeatSheetID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Sequence,
            
            SwimEventID,
            
            HeatSheetEventID,
            
            Distance,
            
            HeatSheetID,
        }
    }
}
