namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _HeatSwimmer class is the base class representing a single HeatSwimmer object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/20/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _HeatSwimmer : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _LaneNumber;
        
        private int _HeatID;
        
        private int _HeatSwimmerID;
        
        private int _SwimmerTeamSeasonID;
        
        private int _Leg;
        
        private int _SeedResultID;
        #endregion
        
        #region  Constructor 
        public _HeatSwimmer()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int LaneNumber
        {
            get
            {
                return _LaneNumber;
            }
            set
            {
                _LaneNumber = value;
            }
        }
        
        public virtual int HeatID
        {
            get
            {
                return _HeatID;
            }
            set
            {
                _HeatID = value;
            }
        }
        
        public virtual int HeatSwimmerID
        {
            get
            {
                return _HeatSwimmerID;
            }
            set
            {
                _HeatSwimmerID = value;
            }
        }
        
        public virtual int SwimmerTeamSeasonID
        {
            get
            {
                return _SwimmerTeamSeasonID;
            }
            set
            {
                _SwimmerTeamSeasonID = value;
            }
        }
        
        public virtual int Leg
        {
            get
            {
                return _Leg;
            }
            set
            {
                _Leg = value;
            }
        }
        
        public virtual int SeedResultID
        {
            get
            {
                return _SeedResultID;
            }
            set
            {
                _SeedResultID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            LaneNumber,
            
            HeatID,
            
            HeatSwimmerID,
            
            SwimmerTeamSeasonID,
            
            Leg,
            
            SeedResultID,
        }
    }
}
