namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _HeatSheetTeam class is the base class representing a single HeatSheetTeam object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/13/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _HeatSheetTeam : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _HeatSheetID;
        
        private int _HeatSheetTeamID;
        
        private string _Lanes;
        
        private int _TeamSeasonID;
        #endregion
        
        #region  Constructor 
        public _HeatSheetTeam()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int HeatSheetID
        {
            get
            {
                return _HeatSheetID;
            }
            set
            {
                _HeatSheetID = value;
            }
        }
        
        public virtual int HeatSheetTeamID
        {
            get
            {
                return _HeatSheetTeamID;
            }
            set
            {
                _HeatSheetTeamID = value;
            }
        }
        
        public virtual string Lanes
        {
            get
            {
                return _Lanes;
            }
            set
            {
                _Lanes = value;
            }
        }
        
        public virtual int TeamSeasonID
        {
            get
            {
                return _TeamSeasonID;
            }
            set
            {
                _TeamSeasonID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            HeatSheetID,
            
            HeatSheetTeamID,
            
            Lanes,
            
            TeamSeasonID,
        }
    }
}
