namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _HeatSheet class is the base class representing a single HeatSheet object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _HeatSheet : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _HeatSheetID;
        
        private int _PoolConfigID;
        
        private int _SwimMeetID;
        #endregion
        
        #region  Constructor 
        public _HeatSheet()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int HeatSheetID
        {
            get
            {
                return _HeatSheetID;
            }
            set
            {
                _HeatSheetID = value;
            }
        }
        
        public virtual int PoolConfigID
        {
            get
            {
                return _PoolConfigID;
            }
            set
            {
                _PoolConfigID = value;
            }
        }
        
        public virtual int SwimMeetID
        {
            get
            {
                return _SwimMeetID;
            }
            set
            {
                _SwimMeetID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            HeatSheetID,
            
            PoolConfigID,
            
            SwimMeetID,
        }
    }
}
