namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _LaneSequence class is the base class representing a single LaneSequence object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 01/06/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _LaneSequence : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _LaneCount;
        
        private int _LaneNumber;
        
        private int _LaneOrder;
        #endregion
        
        #region  Constructor 
        public _LaneSequence()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int LaneCount
        {
            get
            {
                return _LaneCount;
            }
            set
            {
                _LaneCount = value;
            }
        }
        
        public virtual int LaneNumber
        {
            get
            {
                return _LaneNumber;
            }
            set
            {
                _LaneNumber = value;
            }
        }
        
        public virtual int LaneOrder
        {
            get
            {
                return _LaneOrder;
            }
            set
            {
                _LaneOrder = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            LaneCount,
            
            LaneNumber,
            
            LaneOrder,
        }
    }
}
