namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _League class is the base class representing a single League object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 01/11/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _League : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private int _LeagueID;
        
        private string _LeagueName;
        
        private int _RegionID;
        #endregion
        
        #region  Constructor 
        public _League()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int LeagueID
        {
            get
            {
                return _LeagueID;
            }
            set
            {
                _LeagueID = value;
            }
        }
        
        public virtual string LeagueName
        {
            get
            {
                return _LeagueName;
            }
            set
            {
                _LeagueName = value;
            }
        }
        
        public virtual int RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                _RegionID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            LeagueID,
            
            LeagueName,
            
            RegionID,
        }
    }
}
