namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Location class is the base class representing a single Location object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 02/21/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Location : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Address;
        
        private string _City;
        
        private int _LocationID;
        
        private string _Name;
        
        private string _PostalCode;
        
        private int _RegionID;
        
        private int _CreatedByUserID;
        
        private System.DateTime _CreatedDate;
        
        private int _ModifiedByUserID;
        
        private System.DateTime _ModifiedDate;
        
        private decimal _Latitude;
        
        private decimal _Longitude;
        #endregion
        
        #region  Constructor 
        public _Location()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }
        
        public virtual string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }
        
        public virtual int LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                _LocationID = value;
            }
        }
        
        public virtual string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }
        
        public virtual string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }
        
        public virtual int RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                _RegionID = value;
            }
        }
        
        public virtual int CreatedByUserID
        {
            get
            {
                return _CreatedByUserID;
            }
            set
            {
                _CreatedByUserID = value;
            }
        }
        
        public virtual System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                _CreatedDate = value;
            }
        }
        
        public virtual int ModifiedByUserID
        {
            get
            {
                return _ModifiedByUserID;
            }
            set
            {
                _ModifiedByUserID = value;
            }
        }
        
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                _ModifiedDate = value;
            }
        }
        
        public virtual decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                _Latitude = value;
            }
        }
        
        public virtual decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                _Longitude = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Address,
            
            City,
            
            LocationID,
            
            Name,
            
            PostalCode,
            
            RegionID,
            
            CreatedByUserID,
            
            CreatedDate,
            
            ModifiedByUserID,
            
            ModifiedDate,
            
            Latitude,
            
            Longitude,
        }
    }
}
