namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _PoolConfig class is the base class representing a single PoolConfig object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/27/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _PoolConfig : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _LaneCount;
        
        private double _LaneLength;
        
        private int _PoolConfigID;
        
        private int _UOMID;
        
        private string _Description;
        
        private int _PoolID;
        
        private int _CreatedByUserID;
        
        private System.DateTime _CreatedDate;
        
        private int _ModifiedByUserID;
        
        private System.DateTime _ModifiedDate;
        #endregion
        
        #region  Constructor 
        public _PoolConfig()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int LaneCount
        {
            get
            {
                return _LaneCount;
            }
            set
            {
                _LaneCount = value;
            }
        }
        
        public virtual double LaneLength
        {
            get
            {
                return _LaneLength;
            }
            set
            {
                _LaneLength = value;
            }
        }
        
        public virtual int PoolConfigID
        {
            get
            {
                return _PoolConfigID;
            }
            set
            {
                _PoolConfigID = value;
            }
        }
        
        public virtual int UOMID
        {
            get
            {
                return _UOMID;
            }
            set
            {
                _UOMID = value;
            }
        }
        
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int PoolID
        {
            get
            {
                return _PoolID;
            }
            set
            {
                _PoolID = value;
            }
        }
        
        public virtual int CreatedByUserID
        {
            get
            {
                return _CreatedByUserID;
            }
            set
            {
                _CreatedByUserID = value;
            }
        }
        
        public virtual System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                _CreatedDate = value;
            }
        }
        
        public virtual int ModifiedByUserID
        {
            get
            {
                return _ModifiedByUserID;
            }
            set
            {
                _ModifiedByUserID = value;
            }
        }
        
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                _ModifiedDate = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            LaneCount,
            
            LaneLength,
            
            PoolConfigID,
            
            UOMID,
            
            Description,
            
            PoolID,
            
            CreatedByUserID,
            
            CreatedDate,
            
            ModifiedByUserID,
            
            ModifiedDate,
        }
    }
}
