namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Pool class is the base class representing a single Pool object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Pool : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private int _LocationID;
        
        private int _PoolID;
        
        private int _CreatedByUserID;
        
        private System.DateTime _CreatedDate;
        
        private int _ModifiedByUserID;
        
        private System.DateTime _ModifiedDate;
        #endregion
        
        #region  Constructor 
        public _Pool()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                _LocationID = value;
            }
        }
        
        public virtual int PoolID
        {
            get
            {
                return _PoolID;
            }
            set
            {
                _PoolID = value;
            }
        }
        
        public virtual int CreatedByUserID
        {
            get
            {
                return _CreatedByUserID;
            }
            set
            {
                _CreatedByUserID = value;
            }
        }
        
        public virtual System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                _CreatedDate = value;
            }
        }
        
        public virtual int ModifiedByUserID
        {
            get
            {
                return _ModifiedByUserID;
            }
            set
            {
                _ModifiedByUserID = value;
            }
        }
        
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                _ModifiedDate = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            LocationID,
            
            PoolID,
            
            CreatedByUserID,
            
            CreatedDate,
            
            ModifiedByUserID,
            
            ModifiedDate,
        }
    }
}
