namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _ProfileSystemUser class is the base class representing a single ProfileSystemUser object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/26/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _ProfileSystemUser : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _ProfileID;
        
        private int _ProfileSystemUserID;
        
        private int _SystemUserID;
        #endregion
        
        #region  Constructor 
        public _ProfileSystemUser()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int ProfileID
        {
            get
            {
                return _ProfileID;
            }
            set
            {
                _ProfileID = value;
            }
        }
        
        public virtual int ProfileSystemUserID
        {
            get
            {
                return _ProfileSystemUserID;
            }
            set
            {
                _ProfileSystemUserID = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            ProfileID,
            
            ProfileSystemUserID,
            
            SystemUserID,
        }
    }
}
