namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Profile class is the base class representing a single Profile object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/26/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Profile : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private bool _IsActive;
        
        private int _ProfileID;
        
        private string _ProfileName;
        #endregion
        
        #region  Constructor 
        public _Profile()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual bool IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                _IsActive = value;
            }
        }
        
        public virtual int ProfileID
        {
            get
            {
                return _ProfileID;
            }
            set
            {
                _ProfileID = value;
            }
        }
        
        public virtual string ProfileName
        {
            get
            {
                return _ProfileName;
            }
            set
            {
                _ProfileName = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            IsActive,
            
            ProfileID,
            
            ProfileName,
        }
    }
}
