namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _ReportHeatSheetEvent class is the base class representing a single ReportHeatSheetEvent object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 11/16/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _ReportHeatSheetEvent : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _HeatSheetEventID;
        
        private string _SwimmerName;
        
        private string _EventDescription;
        
        private int _LaneNumber;
        
        private int _LaneCount;
        
        private int _HeatNumber;
        
        private int _HeatID;
        
        private int _Sequence;
        
        private int _Leg;
        
        private decimal _SeedTime;
        
        private string _RelayTeam;
        
        private int _Age;
        
        private string _TeamAbbrev;
        
        private string _TeamName;
        #endregion
        
        #region  Constructor 
        public _ReportHeatSheetEvent()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int HeatSheetEventID
        {
            get
            {
                return _HeatSheetEventID;
            }
            set
            {
                _HeatSheetEventID = value;
            }
        }
        
        public virtual string SwimmerName
        {
            get
            {
                return _SwimmerName;
            }
            set
            {
                _SwimmerName = value;
            }
        }
        
        public virtual string EventDescription
        {
            get
            {
                return _EventDescription;
            }
            set
            {
                _EventDescription = value;
            }
        }
        
        public virtual int LaneNumber
        {
            get
            {
                return _LaneNumber;
            }
            set
            {
                _LaneNumber = value;
            }
        }
        
        public virtual int LaneCount
        {
            get
            {
                return _LaneCount;
            }
            set
            {
                _LaneCount = value;
            }
        }
        
        public virtual int HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                _HeatNumber = value;
            }
        }
        
        public virtual int HeatID
        {
            get
            {
                return _HeatID;
            }
            set
            {
                _HeatID = value;
            }
        }
        
        public virtual int Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                _Sequence = value;
            }
        }
        
        public virtual int Leg
        {
            get
            {
                return _Leg;
            }
            set
            {
                _Leg = value;
            }
        }
        
        public virtual decimal SeedTime
        {
            get
            {
                return _SeedTime;
            }
            set
            {
                _SeedTime = value;
            }
        }
        
        public virtual string RelayTeam
        {
            get
            {
                return _RelayTeam;
            }
            set
            {
                _RelayTeam = value;
            }
        }
        
        public virtual int Age
        {
            get
            {
                return _Age;
            }
            set
            {
                _Age = value;
            }
        }
        
        public virtual string TeamAbbrev
        {
            get
            {
                return _TeamAbbrev;
            }
            set
            {
                _TeamAbbrev = value;
            }
        }
        
        public virtual string TeamName
        {
            get
            {
                return _TeamName;
            }
            set
            {
                _TeamName = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            HeatSheetEventID,
            
            SwimmerName,
            
            EventDescription,
            
            LaneNumber,
            
            LaneCount,
            
            HeatNumber,
            
            HeatID,
            
            Sequence,
            
            Leg,
            
            SeedTime,
            
            RelayTeam,
            
            Age,
            
            TeamAbbrev,
            
            TeamName,
        }
    }
}
