namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Role class is the base class representing a single Role object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/26/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Role : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private bool _IsActive;
        
        private int _RoleID;
        
        private string _RoleName;
        #endregion
        
        #region  Constructor 
        public _Role()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual bool IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                _IsActive = value;
            }
        }
        
        public virtual int RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                _RoleID = value;
            }
        }
        
        public virtual string RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                _RoleName = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            IsActive,
            
            RoleID,
            
            RoleName,
        }
    }
}
