namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Score class is the base class representing a single Score object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 02/16/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Score : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SwimMeetID;
        
        private bool _Disqualified;
        
        private int _TeamID;
        
        private double _ElapsedTime;
        
        private string _Swimmer;
        
        private double _LaneLength;
        
        private string _Abbrev;
        
        private string _Description;
        
        private int _SwimmerID;
        
        private bool _IsRelay;
        
        private System.DateTime _EventDate;
        
        private double _Split;
        
        private bool _IsCertified;
        
        private bool _IsProtested;
        
        private int _Place;
        
        private double _Points;
        
        private int _HeatSheetID;
        
        private int _Sequence;
        
        private int _HeatSwimmerID;
        
        private int _HeatSheetEventID;
        
        private int _Leg;
        #endregion
        
        #region  Constructor 
        public _Score()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SwimMeetID
        {
            get
            {
                return _SwimMeetID;
            }
            set
            {
                _SwimMeetID = value;
            }
        }
        
        public virtual bool Disqualified
        {
            get
            {
                return _Disqualified;
            }
            set
            {
                _Disqualified = value;
            }
        }
        
        public virtual int TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                _TeamID = value;
            }
        }
        
        public virtual double ElapsedTime
        {
            get
            {
                return _ElapsedTime;
            }
            set
            {
                _ElapsedTime = value;
            }
        }
        
        public virtual string Swimmer
        {
            get
            {
                return _Swimmer;
            }
            set
            {
                _Swimmer = value;
            }
        }
        
        public virtual double LaneLength
        {
            get
            {
                return _LaneLength;
            }
            set
            {
                _LaneLength = value;
            }
        }
        
        public virtual string Abbrev
        {
            get
            {
                return _Abbrev;
            }
            set
            {
                _Abbrev = value;
            }
        }
        
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int SwimmerID
        {
            get
            {
                return _SwimmerID;
            }
            set
            {
                _SwimmerID = value;
            }
        }
        
        public virtual bool IsRelay
        {
            get
            {
                return _IsRelay;
            }
            set
            {
                _IsRelay = value;
            }
        }
        
        public virtual System.DateTime EventDate
        {
            get
            {
                return _EventDate;
            }
            set
            {
                _EventDate = value;
            }
        }
        
        public virtual double Split
        {
            get
            {
                return _Split;
            }
            set
            {
                _Split = value;
            }
        }
        
        public virtual bool IsCertified
        {
            get
            {
                return _IsCertified;
            }
            set
            {
                _IsCertified = value;
            }
        }
        
        public virtual bool IsProtested
        {
            get
            {
                return _IsProtested;
            }
            set
            {
                _IsProtested = value;
            }
        }
        
        public virtual int Place
        {
            get
            {
                return _Place;
            }
            set
            {
                _Place = value;
            }
        }
        
        public virtual double Points
        {
            get
            {
                return _Points;
            }
            set
            {
                _Points = value;
            }
        }
        
        public virtual int HeatSheetID
        {
            get
            {
                return _HeatSheetID;
            }
            set
            {
                _HeatSheetID = value;
            }
        }
        
        public virtual int Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                _Sequence = value;
            }
        }
        
        public virtual int HeatSwimmerID
        {
            get
            {
                return _HeatSwimmerID;
            }
            set
            {
                _HeatSwimmerID = value;
            }
        }
        
        public virtual int HeatSheetEventID
        {
            get
            {
                return _HeatSheetEventID;
            }
            set
            {
                _HeatSheetEventID = value;
            }
        }
        
        public virtual int Leg
        {
            get
            {
                return _Leg;
            }
            set
            {
                _Leg = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SwimMeetID,
            
            Disqualified,
            
            TeamID,
            
            ElapsedTime,
            
            Swimmer,
            
            LaneLength,
            
            Abbrev,
            
            Description,
            
            SwimmerID,
            
            IsRelay,
            
            EventDate,
            
            Split,
            
            IsCertified,
            
            IsProtested,
            
            Place,
            
            Points,
            
            HeatSheetID,
            
            Sequence,
            
            HeatSwimmerID,
            
            HeatSheetEventID,
            
            Leg,
        }
    }
}
