namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _ScoringScheme class is the base class representing a single ScoringScheme object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 04/20/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _ScoringScheme : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private string _IndividualPoints;
        
        private bool _IsUSASwimming;
        
        private int _LaneCount;
        
        private string _RelayPoints;
        
        private int _ScoringEventTypeID;
        
        private int _ScoringSchemeID;
        #endregion
        
        #region  Constructor 
        public _ScoringScheme()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual string IndividualPoints
        {
            get
            {
                return _IndividualPoints;
            }
            set
            {
                _IndividualPoints = value;
            }
        }
        
        public virtual bool IsUSASwimming
        {
            get
            {
                return _IsUSASwimming;
            }
            set
            {
                _IsUSASwimming = value;
            }
        }
        
        public virtual int LaneCount
        {
            get
            {
                return _LaneCount;
            }
            set
            {
                _LaneCount = value;
            }
        }
        
        public virtual string RelayPoints
        {
            get
            {
                return _RelayPoints;
            }
            set
            {
                _RelayPoints = value;
            }
        }
        
        public virtual int ScoringEventTypeID
        {
            get
            {
                return _ScoringEventTypeID;
            }
            set
            {
                _ScoringEventTypeID = value;
            }
        }
        
        public virtual int ScoringSchemeID
        {
            get
            {
                return _ScoringSchemeID;
            }
            set
            {
                _ScoringSchemeID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            IndividualPoints,
            
            IsUSASwimming,
            
            LaneCount,
            
            RelayPoints,
            
            ScoringEventTypeID,
            
            ScoringSchemeID,
        }
    }
}
