namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Season class is the base class representing a single Season object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Season : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private System.DateTime _EndDate;
        
        private int _SeasonID;
        
        private System.DateTime _StartDate;
        
        private int _LeagueID;
        
        private int _AgeClassRuleID;
        
        private System.DateTime _AgeClassRuleCustomDate;
        #endregion
        
        #region  Constructor 
        public _Season()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                _EndDate = value;
            }
        }
        
        public virtual int SeasonID
        {
            get
            {
                return _SeasonID;
            }
            set
            {
                _SeasonID = value;
            }
        }
        
        public virtual System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                _StartDate = value;
            }
        }
        
        public virtual int LeagueID
        {
            get
            {
                return _LeagueID;
            }
            set
            {
                _LeagueID = value;
            }
        }
        
        public virtual int AgeClassRuleID
        {
            get
            {
                return _AgeClassRuleID;
            }
            set
            {
                _AgeClassRuleID = value;
            }
        }
        
        public virtual System.DateTime AgeClassRuleCustomDate
        {
            get
            {
                return _AgeClassRuleCustomDate;
            }
            set
            {
                _AgeClassRuleCustomDate = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            EndDate,
            
            SeasonID,
            
            StartDate,
            
            LeagueID,
            
            AgeClassRuleID,
            
            AgeClassRuleCustomDate,
        }
    }
}
