namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimEvent class is the base class representing a single SwimEvent object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SwimEvent : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _AgeClassID;
        
        private string _Description;
        
        private int _StrokeID;
        
        private int _SwimEventID;
        #endregion
        
        #region  Constructor 
        public _SwimEvent()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int AgeClassID
        {
            get
            {
                return _AgeClassID;
            }
            set
            {
                _AgeClassID = value;
            }
        }
        
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int StrokeID
        {
            get
            {
                return _StrokeID;
            }
            set
            {
                _StrokeID = value;
            }
        }
        
        public virtual int SwimEventID
        {
            get
            {
                return _SwimEventID;
            }
            set
            {
                _SwimEventID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            AgeClassID,
            
            Description,
            
            StrokeID,
            
            SwimEventID,
        }
    }
}
