namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Swimmer class is the base class representing a single Swimmer object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Swimmer : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private System.DateTime _BirthDate;
        
        private string _FirstName;
        
        private string _LastName;
        
        private int _SwimmerID;
        
        private bool _IsMale;
        #endregion
        
        #region  Constructor 
        public _Swimmer()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual System.DateTime BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                _BirthDate = value;
            }
        }
        
        public virtual string FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                _FirstName = value;
            }
        }
        
        public virtual string LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                _LastName = value;
            }
        }
        
        public virtual int SwimmerID
        {
            get
            {
                return _SwimmerID;
            }
            set
            {
                _SwimmerID = value;
            }
        }
        
        public virtual bool IsMale
        {
            get
            {
                return _IsMale;
            }
            set
            {
                _IsMale = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            BirthDate,
            
            FirstName,
            
            LastName,
            
            SwimmerID,
            
            IsMale,
        }
    }
}
