namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimmerTeamSeason class is the base class representing a single SwimmerTeamSeason object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SwimmerTeamSeason : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private System.DateTime _EndDate;
        
        private System.DateTime _StartDate;
        
        private int _SwimmerID;
        
        private int _SwimmerTeamSeasonID;
        
        private int _TeamSeasonID;
        #endregion
        
        #region  Constructor 
        public _SwimmerTeamSeason()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                _EndDate = value;
            }
        }
        
        public virtual System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                _StartDate = value;
            }
        }
        
        public virtual int SwimmerID
        {
            get
            {
                return _SwimmerID;
            }
            set
            {
                _SwimmerID = value;
            }
        }
        
        public virtual int SwimmerTeamSeasonID
        {
            get
            {
                return _SwimmerTeamSeasonID;
            }
            set
            {
                _SwimmerTeamSeasonID = value;
            }
        }
        
        public virtual int TeamSeasonID
        {
            get
            {
                return _TeamSeasonID;
            }
            set
            {
                _TeamSeasonID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            EndDate,
            
            StartDate,
            
            SwimmerID,
            
            SwimmerTeamSeasonID,
            
            TeamSeasonID,
        }
    }
}
