namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimMeet class is the base class representing a single SwimMeet object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 04/20/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SwimMeet : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private int _LocationID;
        
        private System.DateTime _StartDate;
        
        private int _SwimMeetID;
        
        private int _SeasonID;
        
        private System.DateTime _EndDate;
        
        private int _SwimMeetTypeID;
        #endregion
        
        #region  Constructor 
        public _SwimMeet()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                _LocationID = value;
            }
        }
        
        public virtual System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                _StartDate = value;
            }
        }
        
        public virtual int SwimMeetID
        {
            get
            {
                return _SwimMeetID;
            }
            set
            {
                _SwimMeetID = value;
            }
        }
        
        public virtual int SeasonID
        {
            get
            {
                return _SeasonID;
            }
            set
            {
                _SeasonID = value;
            }
        }
        
        public virtual System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                _EndDate = value;
            }
        }
        
        public virtual int SwimMeetTypeID
        {
            get
            {
                return _SwimMeetTypeID;
            }
            set
            {
                _SwimMeetTypeID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            LocationID,
            
            StartDate,
            
            SwimMeetID,
            
            SeasonID,
            
            EndDate,
            
            SwimMeetTypeID,
        }
    }
}
