namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimmerTeamRequest class is the base class representing a single SwimmerTeamRequest object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/08/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SwimmerTeamRequest : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private System.DateTime _ApprovalDate;
        
        private int _ApprovalUserID;
        
        private bool _IsApproved;
        
        private System.DateTime _RequestDate;
        
        private int _SwimmerTeamRequestID;
        
        private int _TeamSeasonID;
        
        private int _UserSwimmerID;
        #endregion
        
        #region  Constructor 
        public _SwimmerTeamRequest()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual System.DateTime ApprovalDate
        {
            get
            {
                return _ApprovalDate;
            }
            set
            {
                _ApprovalDate = value;
            }
        }
        
        public virtual int ApprovalUserID
        {
            get
            {
                return _ApprovalUserID;
            }
            set
            {
                _ApprovalUserID = value;
            }
        }
        
        public virtual bool IsApproved
        {
            get
            {
                return _IsApproved;
            }
            set
            {
                _IsApproved = value;
            }
        }
        
        public virtual System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                _RequestDate = value;
            }
        }
        
        public virtual int SwimmerTeamRequestID
        {
            get
            {
                return _SwimmerTeamRequestID;
            }
            set
            {
                _SwimmerTeamRequestID = value;
            }
        }
        
        public virtual int TeamSeasonID
        {
            get
            {
                return _TeamSeasonID;
            }
            set
            {
                _TeamSeasonID = value;
            }
        }
        
        public virtual int UserSwimmerID
        {
            get
            {
                return _UserSwimmerID;
            }
            set
            {
                _UserSwimmerID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            ApprovalDate,
            
            ApprovalUserID,
            
            IsApproved,
            
            RequestDate,
            
            SwimmerTeamRequestID,
            
            TeamSeasonID,
            
            UserSwimmerID,
        }
    }
}
