namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SwimMeetTeam class is the base class representing a single SwimMeetTeam object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 12/19/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SwimMeetTeam : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SwimMeetID;
        
        private int _SwimMeetTeamID;
        
        private int _TeamSeasonID;
        
        private bool _IsHomeTeam;
        #endregion
        
        #region  Constructor 
        public _SwimMeetTeam()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SwimMeetID
        {
            get
            {
                return _SwimMeetID;
            }
            set
            {
                _SwimMeetID = value;
            }
        }
        
        public virtual int SwimMeetTeamID
        {
            get
            {
                return _SwimMeetTeamID;
            }
            set
            {
                _SwimMeetTeamID = value;
            }
        }
        
        public virtual int TeamSeasonID
        {
            get
            {
                return _TeamSeasonID;
            }
            set
            {
                _TeamSeasonID = value;
            }
        }
        
        public virtual bool IsHomeTeam
        {
            get
            {
                return _IsHomeTeam;
            }
            set
            {
                _IsHomeTeam = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SwimMeetID,
            
            SwimMeetTeamID,
            
            TeamSeasonID,
            
            IsHomeTeam,
        }
    }
}
