namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _SystemUser class is the base class representing a single SystemUser object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 06/24/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _SystemUser : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private bool _IsActive;
        
        private string _Password;
        
        private int _SystemUserID;
        
        private string _UserName;
        
        private bool _ResetPassword;
        
        private System.Guid _RegistrationKey;
        
        private string _Email;
        
        private System.DateTime _CreateDate;
        
        private string _LastName;
        
        private string _FirstName;
        
        private string _City;
        
        private int _RegionID;
        
        private string _TemporaryPassword;
        
        private System.DateTime _ModifiedDate;
        #endregion
        
        #region  Constructor 
        public _SystemUser()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual bool IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                _IsActive = value;
            }
        }
        
        public virtual string Password
        {
            get
            {
                return _Password;
            }
            set
            {
                _Password = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual string UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                _UserName = value;
            }
        }
        
        public virtual bool ResetPassword
        {
            get
            {
                return _ResetPassword;
            }
            set
            {
                _ResetPassword = value;
            }
        }
        
        public virtual System.Guid RegistrationKey
        {
            get
            {
                return _RegistrationKey;
            }
            set
            {
                _RegistrationKey = value;
            }
        }
        
        public virtual string Email
        {
            get
            {
                return _Email;
            }
            set
            {
                _Email = value;
            }
        }
        
        public virtual System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                _CreateDate = value;
            }
        }
        
        public virtual string LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                _LastName = value;
            }
        }
        
        public virtual string FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                _FirstName = value;
            }
        }
        
        public virtual string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }
        
        public virtual int RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                _RegionID = value;
            }
        }
        
        public virtual string TemporaryPassword
        {
            get
            {
                return _TemporaryPassword;
            }
            set
            {
                _TemporaryPassword = value;
            }
        }
        
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                _ModifiedDate = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            IsActive,
            
            Password,
            
            SystemUserID,
            
            UserName,
            
            ResetPassword,
            
            RegistrationKey,
            
            Email,
            
            CreateDate,
            
            LastName,
            
            FirstName,
            
            City,
            
            RegionID,
            
            TemporaryPassword,
            
            ModifiedDate,
        }
    }
}
