namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _Team class is the base class representing a single Team object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 02/23/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _Team : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _TeamID;
        
        private string _TeamName;
        
        private string _Abbrev;
        
        private int _HomePoolConfigID;
        #endregion
        
        #region  Constructor 
        public _Team()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                _TeamID = value;
            }
        }
        
        public virtual string TeamName
        {
            get
            {
                return _TeamName;
            }
            set
            {
                _TeamName = value;
            }
        }
        
        public virtual string Abbrev
        {
            get
            {
                return _Abbrev;
            }
            set
            {
                _Abbrev = value;
            }
        }
        
        public virtual int HomePoolConfigID
        {
            get
            {
                return _HomePoolConfigID;
            }
            set
            {
                _HomePoolConfigID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            TeamID,
            
            TeamName,
            
            Abbrev,
            
            HomePoolConfigID,
        }
    }
}
