namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _TeamSeason class is the base class representing a single TeamSeason object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _TeamSeason : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SeasonID;
        
        private int _TeamID;
        
        private int _TeamSeasonID;
        
        private int _LeagueID;
        
        private int _AgeClassRuleID;
        #endregion
        
        #region  Constructor 
        public _TeamSeason()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SeasonID
        {
            get
            {
                return _SeasonID;
            }
            set
            {
                _SeasonID = value;
            }
        }
        
        public virtual int TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                _TeamID = value;
            }
        }
        
        public virtual int TeamSeasonID
        {
            get
            {
                return _TeamSeasonID;
            }
            set
            {
                _TeamSeasonID = value;
            }
        }
        
        public virtual int LeagueID
        {
            get
            {
                return _LeagueID;
            }
            set
            {
                _LeagueID = value;
            }
        }
        
        public virtual int AgeClassRuleID
        {
            get
            {
                return _AgeClassRuleID;
            }
            set
            {
                _AgeClassRuleID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SeasonID,
            
            TeamID,
            
            TeamSeasonID,
            
            LeagueID,
            
            AgeClassRuleID,
        }
    }
}
