namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UOM class is the base class representing a single UOM object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 08/03/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UOM : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private string _Description;
        
        private int _UOMID;
        
        private string _Abbrev;
        #endregion
        
        #region  Constructor 
        public _UOM()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }
        
        public virtual int UOMID
        {
            get
            {
                return _UOMID;
            }
            set
            {
                _UOMID = value;
            }
        }
        
        public virtual string Abbrev
        {
            get
            {
                return _Abbrev;
            }
            set
            {
                _Abbrev = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            Description,
            
            UOMID,
            
            Abbrev,
        }
    }
}
