namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserTeam class is the base class representing a single UserTeam object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UserTeam : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SystemUserID;
        
        private int _TeamID;
        
        private int _UserTeamID;
        #endregion
        
        #region  Constructor 
        public _UserTeam()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual int TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                _TeamID = value;
            }
        }
        
        public virtual int UserTeamID
        {
            get
            {
                return _UserTeamID;
            }
            set
            {
                _UserTeamID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SystemUserID,
            
            TeamID,
            
            UserTeamID,
        }
    }
}
