namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserLocation class is the base class representing a single UserLocation object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UserLocation : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _LocationID;
        
        private int _SystemUserID;
        
        private int _UserLocationID;
        #endregion
        
        #region  Constructor 
        public _UserLocation()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                _LocationID = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual int UserLocationID
        {
            get
            {
                return _UserLocationID;
            }
            set
            {
                _UserLocationID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            LocationID,
            
            SystemUserID,
            
            UserLocationID,
        }
    }
}
