namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserSwimmer class is the base class representing a single UserSwimmer object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UserSwimmer : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SwimmerID;
        
        private int _SystemUserID;
        
        private int _UserSwimmerID;
        #endregion
        
        #region  Constructor 
        public _UserSwimmer()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SwimmerID
        {
            get
            {
                return _SwimmerID;
            }
            set
            {
                _SwimmerID = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual int UserSwimmerID
        {
            get
            {
                return _UserSwimmerID;
            }
            set
            {
                _UserSwimmerID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SwimmerID,
            
            SystemUserID,
            
            UserSwimmerID,
        }
    }
}
