namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserSwimMeet class is the base class representing a single UserSwimMeet object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 10/19/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UserSwimMeet : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _SwimMeetID;
        
        private int _SystemUserID;
        
        private int _UserSwimMeetID;
        #endregion
        
        #region  Constructor 
        public _UserSwimMeet()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int SwimMeetID
        {
            get
            {
                return _SwimMeetID;
            }
            set
            {
                _SwimMeetID = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual int UserSwimMeetID
        {
            get
            {
                return _UserSwimMeetID;
            }
            set
            {
                _UserSwimMeetID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            SwimMeetID,
            
            SystemUserID,
            
            UserSwimMeetID,
        }
    }
}
