namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The _UserLeague class is the base class representing a single UserLeague object.
    // This class should not be modified manually.
    // </summary>
    // <history>
    // 		[Updated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class _UserLeague : LAAF.Core.LAEntity
    {
        
        #region  Private Members 
        private int _LeagueID;
        
        private int _SystemUserID;
        
        private int _UserLeagueID;
        #endregion
        
        #region  Constructor 
        public _UserLeague()
        {
        }
        #endregion
        
        #region  Public Properties 
        public virtual int LeagueID
        {
            get
            {
                return _LeagueID;
            }
            set
            {
                _LeagueID = value;
            }
        }
        
        public virtual int SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                _SystemUserID = value;
            }
        }
        
        public virtual int UserLeagueID
        {
            get
            {
                return _UserLeagueID;
            }
            set
            {
                _UserLeagueID = value;
            }
        }
        #endregion
        
        public enum PropertyNames
        {
            
            LeagueID,
            
            SystemUserID,
            
            UserLeagueID,
        }
    }
}
