namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The AgeClassRuleCollection class is the concrete class representing multiple AgeClassRule objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 08/05/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class AgeClassRuleCollection : LAAF.Core.LAEntityCollection<AgeClassRule>
    {
        
        #region  Constructor 
        public AgeClassRuleCollection()
        {
        }
        #endregion
    }
}
