namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The AgeClassRule class is the concrete class representing a single AgeClassRule object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 08/05/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class AgeClassRule : _AgeClassRule
    {
        
        #region  Constructor 
        public AgeClassRule()
        {
        }
        #endregion
    }
}
