namespace Swimomatic.Entity
{


    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The HeatSwimmer class is the concrete class representing a single HeatSwimmer object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class HeatSwimmer : _HeatSwimmer
    {

        #region  Constructor
        public HeatSwimmer()
        {
        }
        #endregion

        #region Properties
        public bool Disqualified { get; set; }
        public double ElapsedTime { get; set; }
        public double Points { get; set; }
        public int Place  { get; set; }
        public int Sequence  { get; set; }
        public double Split { get; set; }
        public string Description { get; set; }
        public string Abbrev { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string LastFirstName { get { return (string.IsNullOrEmpty(this.LastName)) ? string.Empty : this.LastName + ", " + this.FirstName; } }
        public double SeedTime { get; set; }
        public int HeatSheetEventID  { get; set; }
        public int HeatSheetID  { get; set; }
        #endregion

    }
}
