namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The HeatSheetCollection class is the concrete class representing multiple HeatSheet objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class HeatSheetCollection : LAAF.Core.LAEntityCollection<HeatSheet>
    {
        
        #region  Constructor 
        public HeatSheetCollection()
        {
        }
        #endregion
    }
}
