namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The HeatSheet class is the concrete class representing a single HeatSheet object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class HeatSheet : _HeatSheet
    {
        
        #region  Constructor 
        public HeatSheet()
        {
        }
        #endregion
    }
}
