namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The HeatSheetEvent class is the concrete class representing a single HeatSheetEvent object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 10/06/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class HeatSheetEvent : _HeatSheetEvent
    {
        
        #region  Constructor 
        public HeatSheetEvent()
        {
        }
        #endregion

        #region  Properties
        public string Description { get; set; }
        #endregion

    }
}
