namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The LaneSequenceCollection class is the concrete class representing multiple LaneSequence objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 01/06/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class LaneSequenceCollection : LAAF.Core.LAEntityCollection<LaneSequence>
    {
        
        #region  Constructor 
        public LaneSequenceCollection()
        {
        }
        #endregion
    }
}
