namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The LaneSequence class is the concrete class representing a single LaneSequence object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 01/06/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class LaneSequence : _LaneSequence
    {
        
        #region  Constructor 
        public LaneSequence()
        {
        }
        #endregion
    }
}
