using System;
namespace Swimomatic.Entity
{


    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The League class is the concrete class representing a single League object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 07/15/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class League : _League, IEquatable<League>
    {

        #region  Constructor
        public League()
        {
        }
        #endregion

        #region IEquatable
        public bool Equals(League other)
        {
            return (this.LeagueID == other.LeagueID);
        }
        #endregion

        public string SeasonDescription { get; set; }
        public string RegionAbbrev { get; set; }
        public bool IsAdmin { get; set; }
    }
}
