namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The LeagueCollection class is the concrete class representing multiple League objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 07/15/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class LeagueCollection : LAAF.Core.LAEntityCollection<League>
    {
        
        #region  Constructor 
        public LeagueCollection()
        {
        }
        #endregion
    }
}
