namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Location class is the concrete class representing a single Location object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Location : _Location
    {
        
        #region  Constructor 
        public Location()
        {
        }
        #endregion

        public virtual string RegionAbbrev { get; set; }
        public virtual int PoolCount { get; set; }

    }
}
