namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The PoolCollection class is the concrete class representing multiple Pool objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class PoolCollection : LAAF.Core.LAEntityCollection<Pool>
    {
        
        #region  Constructor 
        public PoolCollection()
        {
        }
        #endregion
    }
}
