namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Region class is the concrete class representing a single Region object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Region : _Region
    {
        
        #region  Constructor 
        public Region()
        {
        }
        #endregion
    }
}
