namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The RegionCollection class is the concrete class representing multiple Region objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class RegionCollection : LAAF.Core.LAEntityCollection<Region>
    {
        
        #region  Constructor 
        public RegionCollection()
        {
        }
        #endregion
    }
}
