namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The ReportHeatSheetEvent class is the concrete class representing a single ReportHeatSheetEvent object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 10/17/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class ReportHeatSheetEvent : _ReportHeatSheetEvent
    {
        
        #region  Constructor 
        public ReportHeatSheetEvent()
        {
        }
        #endregion
    }
}
