namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The ReportHeatSheetEventCollection class is the concrete class representing multiple ReportHeatSheetEvent objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 10/17/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class ReportHeatSheetEventCollection : LAAF.Core.LAEntityCollection<ReportHeatSheetEvent>
    {
        
        #region  Constructor 
        public ReportHeatSheetEventCollection()
        {
        }
        #endregion
    }
}
