namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The ResultCollection class is the concrete class representing multiple Result objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 07/19/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class ResultCollection : LAAF.Core.LAEntityCollection<Result>
    {
        
        #region  Constructor 
        public ResultCollection()
        {
        }
        #endregion
    }
}
