namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Role class is the concrete class representing a single Role object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 08/26/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Role : _Role
    {
        
        #region  Constructor 
        public Role()
        {
        }
        #endregion
    }
}
