namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The ScoringSchemeCollection class is the concrete class representing multiple ScoringScheme objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 01/10/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class ScoringSchemeCollection : LAAF.Core.LAEntityCollection<ScoringScheme>
    {
        
        #region  Constructor 
        public ScoringSchemeCollection()
        {
        }
        #endregion
    }
}
