namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The ScoreCollection class is the concrete class representing multiple Score objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 02/12/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class ScoreCollection : LAAF.Core.LAEntityCollection<Score>
    {
        
        #region  Constructor 
        public ScoreCollection()
        {
        }
        #endregion
    }
}
