namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Score class is the concrete class representing a single Score object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 02/12/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Score : _Score
    {
        
        #region  Constructor 
        public Score()
        {
        }
        #endregion
    }
}
