namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SeasonScoringSchemeCollection class is the concrete class representing multiple SeasonScoringScheme objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 01/11/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SeasonScoringSchemeCollection : LAAF.Core.LAEntityCollection<SeasonScoringScheme>
    {
        
        #region  Constructor 
        public SeasonScoringSchemeCollection()
        {
        }
        #endregion
    }
}
