namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SeasonScoringScheme class is the concrete class representing a single SeasonScoringScheme object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 01/11/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SeasonScoringScheme : _SeasonScoringScheme
    {
        
        #region  Constructor 
        public SeasonScoringScheme()
        {
        }
        #endregion
    }
}
