namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Split class is the concrete class representing a single Split object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 01/31/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Split : _Split
    {
        
        #region  Constructor 
        public Split()
        {
        }
        #endregion
    }
}
