namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SplitCollection class is the concrete class representing multiple Split objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Updated on 01/31/2011] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SplitCollection : LAAF.Core.LAEntityCollection<Split>
    {
        
        #region  Constructor 
        public SplitCollection()
        {
        }
        #endregion
    }
}
