namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SwimMeetEventCollection class is the concrete class representing multiple SwimMeetEvent objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SwimMeetEventCollection : LAAF.Core.LAEntityCollection<SwimMeetEvent>
    {
        
        #region  Constructor 
        public SwimMeetEventCollection()
        {
        }
        #endregion
    }
}
