namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SwimMeetEvent class is the concrete class representing a single SwimMeetEvent object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SwimMeetEvent : _SwimMeetEvent
    {
        
        #region  Constructor 
        public SwimMeetEvent()
        {
        }
        #endregion
        
        #region  Properties
        public string Description { get; set; }
        #endregion

    }
}
