namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SwimmerTeamRequest class is the concrete class representing a single SwimmerTeamRequest object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 12/08/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SwimmerTeamRequest : _SwimmerTeamRequest
    {
        
        #region  Constructor 
        public SwimmerTeamRequest()
        {
        }
        #endregion
    }
}
