namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SwimmerTeamRequestCollection class is the concrete class representing multiple SwimmerTeamRequest objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 12/08/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SwimmerTeamRequestCollection : LAAF.Core.LAEntityCollection<SwimmerTeamRequest>
    {
        
        #region  Constructor 
        public SwimmerTeamRequestCollection()
        {
        }
        #endregion
    }
}
