namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The SystemUserCollection class is the concrete class representing multiple SystemUser objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 08/26/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class SystemUserCollection : LAAF.Core.LAEntityCollection<SystemUser>
    {
        
        #region  Constructor 
        public SystemUserCollection()
        {
        }
        #endregion
    }
}
