namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The TeamLeagueRequestCollection class is the concrete class representing multiple TeamLeagueRequest objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 12/08/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class TeamLeagueRequestCollection : LAAF.Core.LAEntityCollection<TeamLeagueRequest>
    {
        
        #region  Constructor 
        public TeamLeagueRequestCollection()
        {
        }
        #endregion
    }
}
