using System;
namespace Swimomatic.Entity
{


    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The Team class is the concrete class representing a single Team object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/18/2009] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class Team : _Team, IEquatable<Team>
    {

        #region  Constructor
        public Team()
        {
        }
        #endregion

        #region IEquatable
        public bool Equals(Team other)
        {
            return (this.TeamID == other.TeamID);
        }
        #endregion

        public string TeamNameAbbrev { get { return base.TeamName + " (" + base.Abbrev + ")"; } }
        public bool IsAdmin { get; set; }

        public string Address { get; set; }
        public string City { get; set; }
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public string PostalCode { get; set; }
        public int RegionID { get; set; }

        public int UserTeamID { get; set; }
        public int TeamLeagueRequestID { get; set; }
        public int TeamSeasonID { get; set; }
        public string SeasonDescription { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string LeagueName { get; set; }
        public string PoolDescription { get; set; }
        public string LaneLength { get; set; }
        public int LaneCount { get; set; }
    }
}

