namespace Swimomatic.Entity
{


    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserLocation class is the concrete class representing a single UserLocation object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserLocation : _UserLocation
    {

        #region  Constructor
        public UserLocation()
        {
        }
        #endregion
    }
}
