namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserLocationCollection class is the concrete class representing multiple UserLocation objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/29/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserLocationCollection : LAAF.Core.LAEntityCollection<UserLocation>
    {
        
        #region  Constructor 
        public UserLocationCollection()
        {
        }
        #endregion
    }
}
