namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserTeam class is the concrete class representing a single UserTeam object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserTeam : _UserTeam
    {
        
        #region  Constructor 
        public UserTeam()
        {
        }
        #endregion
    }
}
