namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserSwimmerCollection class is the concrete class representing multiple UserSwimmer objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserSwimmerCollection : LAAF.Core.LAEntityCollection<UserSwimmer>
    {
        
        #region  Constructor 
        public UserSwimmerCollection()
        {
        }
        #endregion
    }
}
