namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserSwimMeet class is the concrete class representing a single UserSwimMeet object.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 10/19/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserSwimMeet : _UserSwimMeet
    {
        
        #region  Constructor 
        public UserSwimMeet()
        {
        }
        #endregion
    }
}
