namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserTeamCollection class is the concrete class representing multiple UserTeam objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 09/09/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserTeamCollection : LAAF.Core.LAEntityCollection<UserTeam>
    {
        
        #region  Constructor 
        public UserTeamCollection()
        {
        }
        #endregion
    }
}
