namespace Swimomatic.Entity
{
    
    
    // Logical Architect Application Framework
    // Logical Architect (LogArch, Inc)
    // www.logicalarchitect.com
    //  
    // <summary>
    // The UserSwimMeetCollection class is the concrete class representing multiple UserSwimMeet objects.
    // This class is where any customizations can be made.
    // </summary>
    // <history>
    // 		[Generated on 10/19/2010] - Generated by LAAF CodeGen
    // </history>
    [System.Serializable()]
    public class UserSwimMeetCollection : LAAF.Core.LAEntityCollection<UserSwimMeet>
    {
        
        #region  Constructor 
        public UserSwimMeetCollection()
        {
        }
        #endregion
    }
}
